
import { WordCard, VideoLesson, WordGroup, Character, ShopItem } from './types';
import wordPlaceholder from './assets/word_placeholder.png';

const ICON_BASE = "https://img.icons8.com/clouds/200/";

const getImageUrl = (name: string) => {
  const nameMap: Record<string, string> = {
    'dad': 'father',
    'pad': 'tablet',
    'glad': 'happy',
    'mad': 'angry',
    'mat': 'rug',
    'rag': 'cloth',
    'wag': 'dog-wagging-tail',
    'brag': 'shouting',
    'tan': 'color-wheel',
    'van': 'delivery-van',
    'ban': 'prohibition',
    'scan': 'barcode-scanner',
    'gap': 'crack',
    'lap': 'sitting-on-lap',
    'wrap': 'gift',
    'ask': 'question-mark',
    'task': 'todo-list',
    'class': 'classroom',
    'sled': 'sleigh',
    'peg': 'clothespin',
    'beg': 'praying',
    'wet': 'raindrop',
    'mess': 'trash',
    'stress': 'headache',
    'progress': 'growth',
    'success': 'trophy',
    'bin': 'trash-can',
    'spin': 'spinner',
    'twin': 'twins',
    'thin': 'slender',
    'drip': 'water-drop',
    'slip': 'slippery-floor',
    'skip': 'jump-rope',
    'tip': 'light-bulb',
    'whip': 'leather-whip',
    'hip': 'pelvis',
    'zip': 'zipper',
    'trip': 'traveler',
    'flip': 'gymnastics',
    'habit': 'routine',
    'spit': 'saliva',
    'quit': 'exit',
    'knit': 'knitting',
    'wit': 'brain',
    'fit': 'fitness',
    'visit': 'tourist',
    'swift': 'fast',
    'jog': 'running',
    'hop': 'rabbit-jumping',
    'pop': 'music',
    'spot': 'target',
    'shot': 'arrow',
    'dot': 'circle',
    'rot': 'rotten-apple',
    'ox': 'bull',
    'bug': 'insect',
    'drum': 'drums',
    'gum': 'bubble-gum',
    'hum': 'singing',
    'pup': 'puppy',
    'plus': 'addition',
    'cut': 'scissors',
    'shut': 'closed-door',
    'ill': 'sick',
    'pill': 'capsule',
    'hill': 'mountain',
    'table': 'desk',
    'trouble': 'warning',
    'double': 'two',
    'uncle': 'man',
    'circle': 'shape',
    'needle': 'sewing',
    'noodle': 'ramen',
    'candle': 'fire',
    'eagle': 'bird',
    'angle': 'geometry',
    'jungle': 'forest',
    'people': 'group',
    'temple': 'shrine',
    'turtle': 'tortoise',
    'little': 'small',
    'bottle': 'flask',
    'music': 'musical-notes',
    'magic': 'magic-wand',
    'comic': 'manga',
    'attack': 'sword',
    'check': 'tick',
    'deck': 'ship-deck',
    'chick': 'baby-chicken',
    'quick': 'fast',
    'pick': 'hand',
    'stick': 'wood',
    'trick': 'magician',
    'lick': 'tongue',
    'sick': 'vomit',
    'knock': 'door',
    'shock': 'surprised',
    'sock': 'socks',
    'mock': 'laughing',
    'cock': 'rooster',
    'truck': 'lorry',
    'luck': 'clover',
    'jacket': 'coat',
    'ticket': 'coupon',
    'pocket': 'pouch',
    'market': 'shop',
    'bucket': 'pail',
    'lunch': 'meal',
    'rich': 'money',
    'much': 'abundance',
    'coach': 'trainer',
    'teach': 'teacher',
    'speech': 'microphone',
    'beach': 'island',
    'reach': 'goal',
    'search': 'magnifying-glass',
    'match': 'stadium',
    'catch': 'glove',
    'watch': 'television',
    'crash': 'collision',
    'ash': 'dust',
    'trash': 'garbage',
    'cash': 'banknotes',
    'wash': 'soap',
    'blush': 'face',
    'rush': 'sprint',
    'bush': 'shrub',
    'wish': 'star',
    'dish': 'plate',
    'finish': 'checkered-flag',
    'rubbish': 'trash',
    'vanish': 'ghost',
    'brush': 'paint-brush',
    'push': 'hand',
    'crush': 'hammer',
    'tomato': 'vegetable',
    'potato': 'tuber',
    'photo': 'camera',
    'laugh': 'happy',
    'enough': 'full',
    'cough': 'sick',
    'math': 'calculator',
    'path': 'trail',
    'bath': 'bathtub',
    'breath': 'lungs',
    'death': 'skull',
    'cloth': 'fabric',
    'both': 'two-fingers',
    'booth': 'stall',
    'tooth': 'dentist',
    'smooth': 'silk',
    'youth': 'young',
    'mouth': 'lips',
    'truth': 'light-bulb',
    'sunny': 'sun',
    'penny': 'coin',
    'funny': 'clown',
    'runner': 'athlete',
    'winner': 'medal',
    'dinner': 'food',
    'ink': 'pen',
    'think': 'idea',
    'drink': 'glass',
    'tank': 'armored-vehicle',
    'bank': 'building',
    'thank': 'handshake',
    'sink': 'anchor',
    'link': 'chain',
    'pink': 'color-wheel',
    'blank': 'paper',
    'rank': 'leaderboard',
    'song': 'music',
    'long': 'ruler',
    'wrong': 'cross',
    'along': 'road',
    'strong': 'muscle',
    'lace': 'shoelace',
    'face': 'smile',
    'race': 'running',
    'space': 'galaxy',
    'pace': 'footsteps',
    'grace': 'swan',
    'trace': 'footprint',
    'place': 'location',
    'wake': 'alarm-clock',
    'lake': 'pond',
    'snake': 'cobra',
    'bake': 'oven',
    'make': 'tools',
    'cake': 'cupcake',
    'take': 'hand',
    'shake': 'handshake',
    'tale': 'book',
    'male': 'man',
    'whale': 'dolphin',
    'gale': 'wind',
    'exhale': 'breath',
    'pale': 'face',
    'cave': 'cavern',
    'grave': 'tombstone',
    'brave': 'knight',
    'rave': 'party',
    'wave': 'ocean',
    'save': 'lifebuoy',
    'aid': 'first-aid',
    'afraid': 'fear',
    'tail': 'animal',
    'nail': 'hammer',
    'wail': 'crying',
    'snail': 'slug',
    'mail': 'envelope',
    'fail': 'cross',
    'train': 'locomotive',
    'pain': 'bandage',
    'gain': 'chart',
    'rain': 'cloud',
    'drain': 'pipe',
    'grain': 'wheat',
    'bait': 'fishing',
    'wait': 'clock',
    'raise': 'hand',
    'praise': 'clapping',
    'day': 'sun',
    'pay': 'money',
    'say': 'speech-bubble',
    'gray': 'color-wheel',
    'play': 'toys',
    'stay': 'house',
    'way': 'road',
    'bay': 'coast',
    'clay': 'pottery',
    'may': 'calendar',
    'hay': 'farm',
    'lay': 'egg',
    'yesterday': 'history',
    'subway': 'train',
    'bee': 'insect',
    'tree': 'forest',
    'see': 'eye',
    'agree': 'handshake',
    'degree': 'graduation-cap',
    'free': 'gift',
    'flee': 'running',
    'seed': 'plant',
    'weed': 'grass',
    'feed': 'feeding',
    'bleed': 'blood',
    'speed': 'fast',
    'succeed': 'trophy',
    'steel': 'metal',
    'wheel': 'tire',
    'feel': 'heart',
    'queen': 'crown',
    'screen': 'monitor',
    'green': 'leaf',
    'deep': 'ocean',
    'jeep': 'car',
    'sleep': 'bed',
    'steep': 'mountain',
    'weep': 'crying',
    'keep': 'safe',
    'sweep': 'broom',
    'creep': 'spider',
    'sheep': 'lamb',
    'meet': 'handshake',
    'street': 'road',
    'sweet': 'candy',
    'pea': 'vegetable',
    'sea': 'ocean',
    'tea': 'cup',
    'weak': 'sick',
    'peak': 'mountain',
    'speak': 'microphone',
    'break': 'broken',
    'leak': 'water',
    'sneak': 'ninja',
    'dream': 'cloud',
    'stream': 'river',
    'scream': 'shouting',
    'bean': 'seed',
    'clean': 'sparkles',
    'eat': 'food',
    'meat': 'steak',
    'neat': 'organized',
    'cheat': 'liar',
    'beat': 'drum',
    'seat': 'chair',
    'nice': 'thumb-up',
    'rice': 'bowl',
    'mice': 'mouse',
    'price': 'tag',
    'twice': 'two',
    'slice': 'pizza',
    'ice': 'cube',
    'dice': 'game',
    'advice': 'light-bulb',
    'voice': 'mouth',
    'choice': 'arrow',
    'service': 'waiter',
    'police': 'badge',
    'notice': 'alert',
    'office': 'desk',
    'ride': 'bicycle',
    'bride': 'wedding',
    'pride': 'medal',
    'tide': 'wave',
    'wide': 'panorama',
    'hide': 'ghost',
    'slide': 'playground',
    'glide': 'skating',
    'side': 'arrow',
    'wife': 'woman',
    'knife': 'blade',
    'life': 'heart',
    'like': 'heart',
    'bike': 'bicycle',
    'hike': 'boots',
    'file': 'folder',
    'pile': 'stack',
    'smile': 'happy',
    'pine': 'tree',
    'vine': 'plant',
    'wine': 'glass',
    'shine': 'sun',
    'line': 'ruler',
    'fine': 'ok',
    'pipe': 'tube',
    'wipe': 'cloth',
    'stripe': 'zebra',
    'fire': 'flame',
    'hire': 'contract',
    'retire': 'old-man',
    'wire': 'cable',
    'tire': 'wheel',
    'wise': 'owl',
    'surprise': 'gift',
    'white': 'color-wheel',
    'write': 'pencil',
    'invite': 'card',
    'site': 'location',
    'kite': 'toy',
    'drive': 'car',
    'alive': 'heart',
    'prize': 'trophy',
    'realize': 'idea',
    'tie': 'necktie',
    'lie': 'bed',
    'pie': 'cake',
    'die': 'skull',
    'high': 'mountain',
    'sigh': 'sad',
    'night': 'moon',
    'light': 'bulb',
    'sight': 'binoculars',
    'right': 'check',
    'fight': 'boxing',
    'bright': 'sun',
    'flight': 'airplane',
    'height': 'ruler',
    'delight': 'happy',
    'shy': 'blush',
    'try': 'climbing',
    'fly': 'bird',
    'sky': 'clouds',
    'fry': 'pan',
    'cry': 'crying',
    'dry': 'desert',
    'coke': 'soda',
    'joke': 'clown',
    'choke': 'cough',
    'smoke': 'cloud',
    'phone': 'smartphone',
    'tone': 'music',
    'stone': 'rock',
    'rope': 'cord',
    'hope': 'star',
    'slope': 'hill',
    'sore': 'bandage',
    'store': 'shop',
    'core': 'center',
    'chore': 'cleaning',
    'bore': 'yawn',
    'more': 'plus',
    'close': 'door',
    'nose': 'smell',
    'rose': 'flower',
    'gold': 'ingot',
    'hold': 'hand',
    'fold': 'paper',
    'old': 'grandfather',
    'cold': 'ice',
    'oat': 'cereal',
    'throat': 'neck',
    'goat': 'animal',
    'coat': 'jacket',
    'boat': 'ship',
    'float': 'buoy',
    'window': 'glass',
    'know': 'brain',
    'snow': 'snowflake',
    'show': 'stage',
    'row': 'boat',
    'below': 'arrow',
    'shadow': 'silhouette',
    'blow': 'wind',
    'flow': 'river',
    'glow': 'bulb',
    'grow': 'plant',
    'low': 'arrow',
    'slow': 'snail',
    'willow': 'tree',
    'yellow': 'color-wheel',
    'pillow': 'bed',
    'crow': 'bird',
    'borrow': 'hand',
    'arrow': 'bow',
    'due': 'calendar',
    'cue': 'hint',
    'glue': 'paste',
    'clue': 'magnifying-glass',
    'blue': 'color-wheel',
    'dew': 'water-drop',
    'few': 'dots',
    'new': 'sparkles',
    'suit': 'clothing',
    'fruit': 'apple',
    'zoo': 'animals',
    'bamboo': 'plant',
    'kangaroo': 'animal',
    'noon': 'sun',
    'balloon': 'party',
    'moon': 'night'
  };
  const keyword = nameMap[name.toLowerCase()] || name.toLowerCase().replace(/\s+/g, '-');
  return `https://img.icons8.com/fluency/200/${keyword}.png`;
};

const getShopImageUrl = (name: string) => {
  // Map Chinese names to English keywords for more reliable image fetching
  const nameMap: Record<string, string> = {
    '无畏剑士': 'warrior',
    '奇幻女巫': 'witch',
    '灵动狐仙': 'fox',
    '潜行暗影': 'ninja',
    '破魔者之剑': 'sword',
    '狮心盾': 'shield',
    '皇家卫队蓝甲': 'armor',
    '勇气头盔': 'helmet',
    '高级经验药水': 'potion',
    '魔法咒语书': 'book',
    '星辰法杖': 'magic-wand',
    '法术魔典': 'spellbook',
    '高阶法袍': 'robe',
    '星光法帽': 'wizard-hat',
    '星光披风': 'cape',
    '森之弓': 'bow',
    '鹰眼箭袋': 'quiver',
    '游侠皮甲套装': 'leather-armor',
    '森林兜帽': 'hood',
    '疾风靴': 'boots',
    '刺客短刃': 'dagger',
    '毒蝎手里剑': 'shuriken',
    '暗影斗篷': 'cloak',
    '影杀面具': 'mask',
    '潜行长靴': 'stealth-boots',
    '经验药水': 'potion',
    '魔法苹果': 'apple',
    '蓝龙宠兽': 'dragon',
    '史莱姆': 'slime'
  };
  const keyword = nameMap[name] || name.toLowerCase().replace(/\s+/g, '-');
  return `https://img.icons8.com/clouds/200/${keyword}.png`;
};

export const CHARACTERS: Character[] = [
  { 
    id: 'c1', 
    name: '无畏剑士', 
    title: 'Aethelred The Brave', 
    description: '身着湛蓝重甲的热血少年，佩戴标志性防风镜与鲜红围巾，眼神坚定。', 
    avatar: '⚔️', 
    color: '#3B82F6',
    portraitUrl: getShopImageUrl('无畏剑士'),
    baseStats: { strength: 15, magic: 5, defense: 12, agility: 8 }
  },
  { 
    id: 'c2', 
    name: '奇幻女巫', 
    title: 'Elara The Enchantress', 
    description: '粉发灵动的少女法师，头戴缀满星辰的宽檐巫师帽，周身环绕奥术流光。', 
    avatar: '🧙‍♀️', 
    color: '#A855F7',
    portraitUrl: getShopImageUrl('奇幻女巫'),
    baseStats: { strength: 5, magic: 20, defense: 6, agility: 10 }
  },
  { 
    id: 'c3', 
    name: '灵动狐仙', 
    title: 'Finn The Forest-Strider', 
    description: '拟人化的翠绿兜帽游侠，拥有敏锐的狐耳与矫健身姿，是森林的守护者。', 
    avatar: '🦊', 
    color: '#10B981',
    portraitUrl: getShopImageUrl('灵动狐仙'),
    baseStats: { strength: 10, magic: 8, defense: 8, agility: 18 }
  },
  { 
    id: 'c4', 
    name: '潜行暗影', 
    title: 'Shadow-Step', 
    description: '隐匿于深渊的刺客，兜帽下仅露出一双猩红炽热的眼眸，动作如鬼魅般迅捷。', 
    avatar: '👤', 
    color: '#64748B',
    portraitUrl: getShopImageUrl('潜行暗影'),
    baseStats: { strength: 12, magic: 10, defense: 8, agility: 20 }
  }
];

export const SHOP_ITEMS: ShopItem[] = [
  // Aethelred The Brave
  { id: 'i1_1', name: '破魔者之剑', description: '散发着幽蓝光芒的水晶巨剑，能够斩断一切虚幻。', price: 1000, type: 'WEAPON', characterId: 'c1', slot: 'RIGHT_HAND', stats: { strength: 10 }, imageUrl: getShopImageUrl('破魔者之剑'), requiredLevel: 1 },
  { id: 'i1_2', name: '狮心盾', description: '厚重的黄金盾牌，刻有咆哮的狮子纹章，坚不可摧。', price: 2000, type: 'OFFHAND', characterId: 'c1', slot: 'LEFT_HAND', stats: { defense: 15 }, imageUrl: getShopImageUrl('狮心盾'), requiredLevel: 3 },
  { id: 'i1_3', name: '皇家卫队蓝甲', description: '精锐卫队专属重甲，兼具防御力与荣耀。', price: 3000, type: 'OUTFIT', characterId: 'c1', slot: 'BODY', stats: { defense: 20, strength: 5 }, imageUrl: getShopImageUrl('皇家卫队蓝甲'), requiredLevel: 5 },
  { id: 'i1_4', name: '勇气头盔', description: '带有红色羽饰的钢盔，象征着永不退缩。', price: 1500, type: 'ARMOR', characterId: 'c1', slot: 'HEAD', stats: { defense: 8 }, imageUrl: getShopImageUrl('勇气头盔'), requiredLevel: 2 },
  { id: 'i1_5', name: '高级经验药水', description: '蕴含强大魔力的药水，能大幅提升英雄经验。', price: 2500, type: 'CONSUMABLE', characterId: 'c1', slot: 'NONE', stats: {}, imageUrl: getShopImageUrl('高级经验药水'), requiredLevel: 4 },
  { id: 'i1_6', name: '魔法咒语书', description: '记载着基础防御咒语的书籍。', price: 500, type: 'CONSUMABLE', characterId: 'c1', slot: 'NONE', stats: { magic: 2 }, imageUrl: getShopImageUrl('魔法咒语书'), requiredLevel: 1 },
  
  // Elara The Enchantress
  { id: 'i2_1', name: '星辰法杖', description: '顶端镶嵌着发光金星的紫色法杖，汇聚星辰之力。', price: 1000, type: 'WEAPON', characterId: 'c2', slot: 'RIGHT_HAND', stats: { magic: 15 }, imageUrl: getShopImageUrl('星辰法杖'), requiredLevel: 1 },
  { id: 'i2_2', name: '法术魔典', description: '记载着古老禁咒的紫色皮质书，漂浮着神秘符文。', price: 2000, type: 'OFFHAND', characterId: 'c2', slot: 'LEFT_HAND', stats: { magic: 10, defense: 5 }, imageUrl: getShopImageUrl('法术魔典'), requiredLevel: 3 },
  { id: 'i2_3', name: '高阶法袍', description: '绣有星辰图案的深紫色长袍，增强魔力感应。', price: 3000, type: 'OUTFIT', characterId: 'c2', slot: 'BODY', stats: { magic: 20, defense: 10 }, imageUrl: getShopImageUrl('高阶法袍'), requiredLevel: 5 },
  { id: 'i2_4', name: '星光法帽', description: '镶嵌着蓝色宝石的银色头冠，提升思维敏捷。', price: 1500, type: 'ARMOR', characterId: 'c2', slot: 'HEAD', stats: { magic: 12 }, imageUrl: getShopImageUrl('星光法帽'), requiredLevel: 2 },
  { id: 'i2_5', name: '星光披风', description: '如夜空般璀璨的半透明披风，如梦似幻。', price: 2500, type: 'OUTFIT', characterId: 'c2', slot: 'BACK', stats: { agility: 12 }, imageUrl: getShopImageUrl('星光披风'), requiredLevel: 4 },
  
  // Finn The Forest-Strider
  { id: 'i3_1', name: '森之弓', description: '由活木制成的长弓，射出的箭矢带有自然气息。', price: 1000, type: 'WEAPON', characterId: 'c3', slot: 'RIGHT_HAND', stats: { agility: 15 }, imageUrl: getShopImageUrl('森之弓'), requiredLevel: 1 },
  { id: 'i3_2', name: '鹰眼箭袋', description: '棕色皮革箭袋，装满翠绿羽毛的利箭。', price: 2000, type: 'OFFHAND', characterId: 'c3', slot: 'BACK', stats: { agility: 10, strength: 5 }, imageUrl: getShopImageUrl('鹰眼箭袋'), requiredLevel: 3 },
  { id: 'i3_3', name: '游侠皮甲套装', description: '轻便的棕色皮甲，适合在森林中快速穿梭。', price: 3000, type: 'OUTFIT', characterId: 'c3', slot: 'BODY', stats: { agility: 20, defense: 10 }, imageUrl: getShopImageUrl('游侠皮甲套装'), requiredLevel: 5 },
  { id: 'i3_4', name: '森林兜帽', description: '饰有小叶子的绿色兜帽，提供极佳的隐蔽性。', price: 1500, type: 'ARMOR', characterId: 'c3', slot: 'HEAD', stats: { agility: 8, defense: 5 }, imageUrl: getShopImageUrl('森林兜帽'), requiredLevel: 2 },
  { id: 'i3_5', name: '疾风靴', description: '带有小翅膀装饰的轻便靴子，健步如飞。', price: 2500, type: 'OUTFIT', characterId: 'c3', slot: 'NONE', stats: { agility: 25 }, imageUrl: getShopImageUrl('疾风靴'), requiredLevel: 4 },
  
  // Shadow-Step
  { id: 'i4_1', name: '刺客短刃', description: '锋利的黑色短剑，剑柄镶有红宝石，散发着杀气。', price: 1000, type: 'WEAPON', characterId: 'c4', slot: 'RIGHT_HAND', stats: { strength: 15 }, imageUrl: getShopImageUrl('刺客短刃'), requiredLevel: 1 },
  { id: 'i4_2', name: '毒蝎手里剑', description: '涂有剧毒的黑色金属手里剑，见血封喉。', price: 2000, type: 'OFFHAND', characterId: 'c4', slot: 'LEFT_HAND', stats: { agility: 15 }, imageUrl: getShopImageUrl('毒蝎手里剑'), requiredLevel: 3 },
  { id: 'i4_3', name: '暗影斗篷', description: '带有红色点缀的深灰色兜帽斗篷，融入阴影。', price: 3000, type: 'OUTFIT', characterId: 'c4', slot: 'BODY', stats: { agility: 20, defense: 10 }, imageUrl: getShopImageUrl('暗影斗篷'), requiredLevel: 5 },
  { id: 'i4_4', name: '影杀面具', description: '遮住下半张脸的黑色布面具，冷酷无情。', price: 1500, type: 'ARMOR', characterId: 'c4', slot: 'HEAD', stats: { agility: 12 }, imageUrl: getShopImageUrl('影杀面具'), requiredLevel: 2 },
  { id: 'i4_5', name: '潜行长靴', description: '走路悄无声息的深灰色靴子，如影随形。', price: 2500, type: 'OUTFIT', characterId: 'c4', slot: 'NONE', stats: { agility: 25 }, imageUrl: getShopImageUrl('潜行长靴'), requiredLevel: 4 },

  // General Items
  { id: 'gen_1', name: '经验药水', description: '散发着绿色荧光的药水，能瞬间提升英雄等级。', price: 500, type: 'CONSUMABLE', characterId: 'all', slot: 'NONE', stats: {}, imageUrl: getShopImageUrl('经验药水') },
  { id: 'gen_2', name: '魔法苹果', description: '咬一口就能恢复大量体力的神奇苹果。', price: 100, type: 'FOOD', characterId: 'all', slot: 'NONE', foodValue: 10, imageUrl: getShopImageUrl('魔法苹果') },
  { id: 'pet_dragon', name: '小蓝龙', description: '忠诚的龙族伙伴，虽然还很小，但能喷出微弱的火焰。', price: 5000, type: 'PET', characterId: 'all', slot: 'NONE', petType: 'DRAGON', imageUrl: getShopImageUrl('蓝龙宠兽') },
  { id: 'pet_slime', name: '波利史莱姆', description: '软绵绵的宠物，虽然看起来很弱，但意外地耐打。', price: 2000, type: 'PET', characterId: 'all', slot: 'NONE', petType: 'SLIME', imageUrl: getShopImageUrl('史莱姆') },
  { id: 'pet_cat', name: '招财猫', description: '能带来好运的小猫，非常贪吃。', price: 3000, type: 'PET', characterId: 'all', slot: 'NONE', petType: 'CAT', imageUrl: getShopImageUrl('cat') },
  { id: 'pet_owl', name: '智慧之鸮', description: '博学多才的猫头鹰，喜欢在夜晚出没。', price: 4000, type: 'PET', characterId: 'all', slot: 'NONE', petType: 'OWL', imageUrl: getShopImageUrl('owl') },
  { id: 'food_meat', name: '优质肉块', description: '恢复 25 点生命值', price: 100, type: 'FOOD', characterId: 'all', slot: 'NONE', foodValue: 25, imageUrl: getShopImageUrl('meat') },
  { id: 'food_elixir', name: '生命灵药', description: '恢复 50 点生命值', price: 200, type: 'FOOD', characterId: 'all', slot: 'NONE', foodValue: 50, imageUrl: getShopImageUrl('potion') },
];

export const ALL_CARDS: WordCard[] = [
  { id: 'c1', suffix: 'ad', levelName: '森林初见', words: [{ text: 'dad', translation: '爸爸', imageUrl: getImageUrl('dad') }, { text: 'bad', translation: '坏的', imageUrl: getImageUrl('bad') }, { text: 'sad', translation: '伤心的', imageUrl: getImageUrl('sad') }], rhyme: '我家 dad (爸爸), 脾气 bad (坏的), 让我 sad (伤心的).', learned: false },
  { id: 'c2', suffix: 'ad', levelName: '森林初见', words: [{ text: 'pad', translation: '平板', imageUrl: getImageUrl('tablet') }, { text: 'glad', translation: '高兴的', imageUrl: getImageUrl('happy') }, { text: 'mad', translation: '生气的', imageUrl: getImageUrl('angry') }], rhyme: '玩着 pad (平板), 心情 glad (高兴的), 爸爸 mad (生气的).', learned: false },
  { id: 'c3', suffix: 'at', levelName: '神秘小径', words: [{ text: 'cat', translation: '猫', imageUrl: getImageUrl('cat') }, { text: 'rat', translation: '老鼠', imageUrl: getImageUrl('rat') }, { text: 'fat', translation: '胖', imageUrl: getImageUrl('fat') }], rhyme: '有只 cat (猫), 专吃 rat (老鼠), 非常 fat (胖).', learned: false },
  { id: 'c4', suffix: 'at', levelName: '神秘小径', words: [{ text: 'rat', translation: '老鼠', imageUrl: getImageUrl('mouse') }, { text: 'mat', translation: '垫子', imageUrl: getImageUrl('mat') }, { text: 'bat', translation: '蝙蝠', imageUrl: getImageUrl('bat') }], rhyme: '一只 rat (老鼠), 绑上 mat (垫子), 假装 bat (蝙蝠).', learned: false },
  { id: 'c5', suffix: 'at', levelName: '清凉溪流', words: [{ text: 'bat', translation: '球棒', imageUrl: getImageUrl('baseball-bat') }, { text: 'hat', translation: '帽子', imageUrl: getImageUrl('hat') }, { text: 'pat', translation: '轻拍', imageUrl: getImageUrl('pat') }], rhyme: '拿上 bat (球棒), 带上 hat (帽子), 把球 pat (轻拍).', learned: false },
  { id: 'c6', suffix: 'at', levelName: '清凉溪流', words: [{ text: 'flat', translation: '平坦', imageUrl: getImageUrl('flat') }, { text: 'mat', translation: '垫子', imageUrl: getImageUrl('rug') }, { text: 'chat', translation: '聊天', imageUrl: getImageUrl('chat') }], rhyme: '地面 flat (平坦), 铺上 mat (垫子), 开心 chat (聊天).', learned: false },
  { id: 'c7', suffix: 'ag', levelName: '古老橡树', words: [{ text: 'rag', translation: '破布', imageUrl: getImageUrl('rag') }, { text: 'flag', translation: '旗子', imageUrl: getImageUrl('flag') }, { text: 'wag', translation: '摇摆', imageUrl: getImageUrl('wag') }], rhyme: '找来 rag (破布), 做成 flag (旗子),随风 wag (摇摆).', learned: false },
  { id: 'c8', suffix: 'ag', levelName: '古老橡树', words: [{ text: 'bag', translation: '包', imageUrl: getImageUrl('bag') }, { text: 'brag', translation: '吹牛', imageUrl: getImageUrl('brag') }, { text: 'tag', translation: '标签', imageUrl: getImageUrl('tag') }], rhyme: '借来 bag (包), 正要 brag (吹牛), 掉出 tag (标签).', learned: false },
  { id: 'c9', suffix: 'an', levelName: '萤火虫谷', words: [{ text: 'man', translation: '男人', imageUrl: getImageUrl('man') }, { text: 'pan', translation: '锅', imageUrl: getImageUrl('pan') }, { text: 'tan', translation: '焦褐色', imageUrl: getImageUrl('tan') }], rhyme: '有个 man (男人), 没看 pan (锅), 烧成 tan (焦褐色).', learned: false },
  { id: 'c10', suffix: 'an', levelName: '萤火虫谷', words: [{ text: 'plan', translation: '计划', imageUrl: getImageUrl('plan') }, { text: 'van', translation: '货车', imageUrl: getImageUrl('van') }, { text: 'fan', translation: '风扇', imageUrl: getImageUrl('fan') }], rhyme: '有个 plan (计划), 换辆 van (货车), 能吹 fan (风扇).', learned: false },
  { id: 'c11', suffix: 'an', levelName: '迷雾森林', words: [{ text: 'ban', translation: '禁令', imageUrl: getImageUrl('ban') }, { text: 'can', translation: '可以', imageUrl: getImageUrl('can') }, { text: 'scan', translation: '扫视', imageUrl: getImageUrl('scan') }], rhyme: '出了 ban (禁令), 没人 can (可以), 偷偷 scan (扫视).', learned: false },
  { id: 'c12', suffix: 'ap', levelName: '迷雾森林', words: [{ text: 'cap', translation: '帽子', imageUrl: getImageUrl('cap') }, { text: 'tap', translation: '轻拍', imageUrl: getImageUrl('tap') }, { text: 'rap', translation: '说唱', imageUrl: getImageUrl('rap') }], rhyme: '带上 cap (帽子), 用手 tap (轻拍), 哼着 rap (说唱).', learned: false },
  { id: 'c13', suffix: 'ap', levelName: '翡翠湖畔', words: [{ text: 'trap', translation: '陷阱', imageUrl: getImageUrl('trap') }, { text: 'gap', translation: '空隙', imageUrl: getImageUrl('gap') }, { text: 'lap', translation: '大腿', imageUrl: getImageUrl('lap') }], rhyme: '掉进 trap (陷阱), 有个 gap (空隙), 伤到 lap (大腿).', learned: false },
  { id: 'c14', suffix: 'ap', levelName: '翡翠湖畔', words: [{ text: 'map', translation: '地图', imageUrl: getImageUrl('map') }, { text: 'wrap', translation: '包裹', imageUrl: getImageUrl('wrap') }, { text: 'gap', translation: '空隙', imageUrl: getImageUrl('gap') }], rhyme: '找到 map (地图), 用纸 wrap (包裹), 藏进 gap (空隙).', learned: false },
  { id: 'c15', suffix: 'and', levelName: '松果高地', words: [{ text: 'hand', translation: '手', imageUrl: getImageUrl('hand') }, { text: 'sand', translation: '沙子', imageUrl: getImageUrl('sand') }, { text: 'land', translation: '陆地', imageUrl: getImageUrl('land') }], rhyme: '我用 hand (手), 拿来 sand (沙子), 填出 land (陆地).', learned: false },
  { id: 'c16', suffix: 'ask', levelName: '松果高地', words: [{ text: 'ask', translation: '问', imageUrl: getImageUrl('ask') }, { text: 'task', translation: '任务', imageUrl: getImageUrl('task') }, { text: 'mask', translation: '面具', imageUrl: getImageUrl('mask') }], rhyme: '过去 ask (问), 今天 task (任务), 戴上 mask (面具).', learned: false },
  { id: 'c17', suffix: 'ass', levelName: '蘑菇森林', words: [{ text: 'class', translation: '课', imageUrl: getImageUrl('class') }, { text: 'glass', translation: '玻璃', imageUrl: getImageUrl('glass') }, { text: 'grass', translation: '草', imageUrl: getImageUrl('grass') }], rhyme: '这节 class (课), 拿上 glass (玻璃镜), 观察 grass (草).', learned: false },
  { id: 'c18', suffix: 'ed', levelName: '蘑菇森林', words: [{ text: 'sled', translation: '雪橇', imageUrl: getImageUrl('sled') }, { text: 'bed', translation: '床', imageUrl: getImageUrl('bed') }, { text: 'red', translation: '红色', imageUrl: getImageUrl('red') }], rhyme: '找来 sled (雪橇), 拉上 bed (床), 颜色 red (红色).', learned: false },
  { id: 'c19', suffix: 'eg', levelName: '飞瀑深潭', words: [{ text: 'leg', translation: '腿', imageUrl: getImageUrl('leg') }, { text: 'peg', translation: '夹子', imageUrl: getImageUrl('peg') }, { text: 'beg', translation: '乞求', imageUrl: getImageUrl('beg') }], rhyme: '两只 leg (腿), 夹上 peg (夹子), 只想 beg (求饶).', learned: false },
  { id: 'c20', suffix: 'en', levelName: '飞瀑深潭', words: [{ text: 'hen', translation: '母鸡', imageUrl: getImageUrl('hen') }, { text: 'pen', translation: '钢笔', imageUrl: getImageUrl('pen') }, { text: 'ten', translation: '十', imageUrl: getImageUrl('ten') }], rhyme: '一只 hen (母鸡), 买了 pen (钢笔), 花了 ten (十).', learned: false },
  { id: 'c21', suffix: 'et', levelName: '幽静山谷', words: [{ text: 'pet', translation: '宠物', imageUrl: getImageUrl('pet') }, { text: 'net', translation: '网', imageUrl: getImageUrl('net') }, { text: 'wet', translation: '潮湿的', imageUrl: getImageUrl('wet') }], rhyme: '养了 pet (宠物), 结出 net (网), 喜欢 wet (潮湿的).', learned: false },
  { id: 'c22', suffix: 'ess', levelName: '幽静山谷', words: [{ text: 'dress', translation: '裙子', imageUrl: getImageUrl('dress') }, { text: 'address', translation: '地址', imageUrl: getImageUrl('address') }, { text: 'mess', translation: '脏乱', imageUrl: getImageUrl('mess') }], rhyme: '想退 dress (裙子), 忘了 address (地址), 一团 mess (脏乱).', learned: false },
  { id: 'c23', suffix: 'ess', levelName: '繁星草地', words: [{ text: 'stress', translation: '压力', imageUrl: getImageUrl('stress') }, { text: 'progress', translation: '进步', imageUrl: getImageUrl('progress') }, { text: 'success', translation: '成功', imageUrl: getImageUrl('success') }], rhyme: '没有 stress (压力), 身上 press (压), 怎么 progress (进步), 别说 success (成功).', learned: false },
  { id: 'c24', suffix: 'ig', levelName: '繁星草地', words: [{ text: 'pig', translation: '猪', imageUrl: getImageUrl('pig') }, { text: 'big', translation: '大', imageUrl: getImageUrl('big') }, { text: 'dig', translation: '挖', imageUrl: getImageUrl('dig') }], rhyme: '一只 pig (猪), 非常 big (大), 喜欢 dig (挖).', learned: false },
  { id: 'c25', suffix: 'in', levelName: '晨曦林间', words: [{ text: 'bin', translation: '桶', imageUrl: getImageUrl('bin') }, { text: 'spin', translation: '旋转', imageUrl: getImageUrl('spin') }, { text: 'win', translation: '赢', imageUrl: getImageUrl('win') }], rhyme: '顶着 bin (桶), 比赛 spin (旋转), 看谁 win (赢).', learned: false },
  { id: 'c26', suffix: 'in', levelName: '晨曦林间', words: [{ text: 'twin', translation: '双胞胎', imageUrl: getImageUrl('twins') }, { text: 'thin', translation: '瘦的', imageUrl: getImageUrl('thin') }, { text: 'pin', translation: '曲别针', imageUrl: getImageUrl('pin') }], rhyme: '一对 twin (双胞胎), 一样 thin (瘦的), 就像 pin (曲别针).', learned: false },
  { id: 'c27', suffix: 'im', levelName: '暮色森林', words: [{ text: 'him', translation: '他', imageUrl: getImageUrl('boy') }, { text: 'swim', translation: '游泳', imageUrl: getImageUrl('swim') }, { text: 'slim', translation: '苗条的', imageUrl: getImageUrl('slim') }], rhyme: '跟着 him (他), 每天 swim (游泳), 身材 slim (苗条的).', learned: false },
  { id: 'c28', suffix: 'ip', levelName: '暮色森林', words: [{ text: 'drip', translation: '滴下', imageUrl: getImageUrl('drip') }, { text: 'slip', translation: '滑的', imageUrl: getImageUrl('slip') }, { text: 'skip', translation: '跳过', imageUrl: getImageUrl('skip') }], rhyme: '水滴 drip (滴下), 地上 slip (滑的), 赶紧 skip (跳过).', learned: false },
  { id: 'c29', suffix: 'ip', levelName: '幻影森林', words: [{ text: 'tip', translation: '建议', imageUrl: getImageUrl('tip') }, { text: 'whip', translation: '鞭子', imageUrl: getImageUrl('whip') }, { text: 'hip', translation: '屁股', imageUrl: getImageUrl('hip') }], rhyme: '给错 tip (建议), 就用 whip (鞭子), 抽你 hip (屁股).', learned: false },
  { id: 'c30', suffix: 'ip', levelName: '幻影森林', words: [{ text: 'tip', translation: '小费', imageUrl: getImageUrl('money') }, { text: 'lip', translation: '嘴唇', imageUrl: getImageUrl('lip') }, { text: 'zip', translation: '拉链', imageUrl: getImageUrl('zip') }], rhyme: '没给 tip (小费), 把你 lip (嘴唇), 装上 zip (拉链).', learned: false },
  { id: 'c31', suffix: 'ip', levelName: '奇迹之花', words: [{ text: 'ship', translation: '船', imageUrl: getImageUrl('ship') }, { text: 'trip', translation: '旅行', imageUrl: getImageUrl('trip') }, { text: 'flip', translation: '翻转', imageUrl: getImageUrl('flip') }], rhyme: '跳上 ship (船), 开启 trip (旅行), 浪花 flip (翻转).', learned: false },
  { id: 'c32', suffix: 'bit', levelName: '奇迹之花', words: [{ text: 'rabbit', translation: '兔子', imageUrl: getImageUrl('rabbit') }, { text: 'habit', translation: '习惯', imageUrl: getImageUrl('habit') }, { text: 'a bit', translation: '一点点', imageUrl: getImageUrl('bit') }], rhyme: '有只 rabbit (兔子), 有个 habit (习惯), 只吃 a bit (一点点).', learned: false },
  { id: 'c33', suffix: 'it', levelName: '智慧之树', words: [{ text: 'spit', translation: '吐口水', imageUrl: getImageUrl('spit') }, { text: 'quit', translation: '停止', imageUrl: getImageUrl('quit') }, { text: 'hit', translation: '打', imageUrl: getImageUrl('hit') }], rhyme: '习惯 spit (吐口水), 劝你 quit (停止), 不然 hit (打).', learned: false },
  { id: 'c34', suffix: 'it', levelName: '智慧之树', words: [{ text: 'knit', translation: '编织', imageUrl: getImageUrl('knit') }, { text: 'wit', translation: '机智', imageUrl: getImageUrl('wit') }, { text: 'fit', translation: '健康的', imageUrl: getImageUrl('fit') }], rhyme: '多去 knit (编织), 头脑 wit (机智), 身体 fit (健康的).', learned: false },
  { id: 'c35', suffix: 'it', levelName: '勇气之泉', words: [{ text: 'sit', translation: '坐', imageUrl: getImageUrl('sit') }, { text: 'visit', translation: '游览', imageUrl: getImageUrl('visit') }, { text: 'fit', translation: '健康的', imageUrl: getImageUrl('healthy') }], rhyme: '别又 sit (坐), 多去 visit (游览), 身体 fit (健康的).', learned: false },
  { id: 'c36', suffix: 'ift', levelName: '勇气之泉', words: [{ text: 'gift', translation: '礼物', imageUrl: getImageUrl('gift') }, { text: 'lift', translation: '电梯', imageUrl: getImageUrl('lift') }, { text: 'swift', translation: '快的', imageUrl: getImageUrl('swift') }], rhyme: '收到 gift (礼物), 装满 lift (电梯), 打开 swift (快的).', learned: false },
  { id: 'c37', suffix: 'og', levelName: '守护者之森', words: [{ text: 'jog', translation: '慢跑', imageUrl: getImageUrl('jog') }, { text: 'dog', translation: '狗', imageUrl: getImageUrl('dog') }, { text: 'frog', translation: '青蛙', imageUrl: getImageUrl('frog') }], rhyme: '清晨 jog (慢跑), 带上 dog (狗), 踩到 frog (青蛙).', learned: false },
  { id: 'c38', suffix: 'op', levelName: '守护者之森', words: [{ text: 'hop', translation: '跳', imageUrl: getImageUrl('hop') }, { text: 'top', translation: '顶部', imageUrl: getImageUrl('top') }, { text: 'pop', translation: '流行', imageUrl: getImageUrl('pop') }], rhyme: '轻轻 hop (跳), 跳上 top (顶部), 唱起 pop (流行音乐).', learned: false },
  { id: 'c39', suffix: 'op', levelName: '永恒森林', words: [{ text: 'shop', translation: '购物', imageUrl: getImageUrl('shop') }, { text: 'stop', translation: '停下', imageUrl: getImageUrl('stop') }, { text: 'mop', translation: '拖把', imageUrl: getImageUrl('mop') }], rhyme: '拼命 shop (购物), 不能 stop (停下), 拿起 mop (拖把).', learned: false },
  { id: 'c40', suffix: 'op', levelName: '永恒森林', words: [{ text: 'spot', translation: '点', imageUrl: getImageUrl('spot') }, { text: 'shot', translation: '射出', imageUrl: getImageUrl('shot') }, { text: 'dot', translation: '小圆点', imageUrl: getImageUrl('dot') }], rhyme: '朝着 spot (点), 用力 shot (射出), 留下 dot (小圆点).', learned: false },
  { id: 'c41', suffix: 'ot', levelName: '远古遗迹', words: [{ text: 'hot', translation: '热', imageUrl: getImageUrl('hot') }, { text: 'rot', translation: '烂了', imageUrl: getImageUrl('rot') }, { text: 'pot', translation: '壶', imageUrl: getImageUrl('pot') }], rhyme: '天气 hot (热), 食物 rot (烂了), 放在 pot (壶).', learned: false },
  { id: 'c42', suffix: 'ox', levelName: '远古遗迹', words: [{ text: 'fox', translation: '狐狸', imageUrl: getImageUrl('fox') }, { text: 'box', translation: '盒子', imageUrl: getImageUrl('box') }, { text: 'ox', translation: '公牛', imageUrl: getImageUrl('ox') }], rhyme: '一只 fox (狐狸), 躲进 box (盒子), 躲过 ox (公牛).', learned: false },
  { id: 'c43', suffix: 'ug', levelName: '巨石阵', words: [{ text: 'bug', translation: '虫子', imageUrl: getImageUrl('bug') }, { text: 'hug', translation: '拥抱', imageUrl: getImageUrl('hug') }, { text: 'dug', translation: '挖', imageUrl: getImageUrl('dug') }], rhyme: '一只 bug (虫子), 把我 hug (拥抱), 把洞 dug (挖).', learned: false },
  { id: 'c44', suffix: 'un', levelName: '巨石阵', words: [{ text: 'sun', translation: '太阳', imageUrl: getImageUrl('sun') }, { text: 'run', translation: '跑步', imageUrl: getImageUrl('run') }, { text: 'fun', translation: '开心', imageUrl: getImageUrl('fun') }], rhyme: '晒着 sun (太阳), 不停 run (跑步), 心情 fun (开心).', learned: false },
  { id: 'c45', suffix: 'um', levelName: '秘密花园', words: [{ text: 'drum', translation: '鼓', imageUrl: getImageUrl('drum') }, { text: 'gum', translation: '口香糖', imageUrl: getImageUrl('gum') }, { text: 'hum', translation: '哼', imageUrl: getImageUrl('hum') }], rhyme: '敲着 drum (鼓), 嚼着 gum (口香糖), 把歌 hum (哼).', learned: false },
  { id: 'c46', suffix: 'up', levelName: '秘密花园', words: [{ text: 'cup', translation: '杯子', imageUrl: getImageUrl('cup') }, { text: 'up', translation: '向上', imageUrl: getImageUrl('up') }, { text: 'pup', translation: '小狗', imageUrl: getImageUrl('pup') }], rhyme: '拿着 cup (杯子), 不断 up (向上), 抱着 pup (小狗).', learned: false },
  { id: 'c47', suffix: 'us', levelName: '蝴蝶谷', words: [{ text: 'bus', translation: '巴士', imageUrl: getImageUrl('bus') }, { text: 'us', translation: '我们', imageUrl: getImageUrl('us') }, { text: 'plus', translation: '加', imageUrl: getImageUrl('plus') }], rhyme: '一辆 bus (巴士), 来接 us (我们), 去学 plus (加法).', learned: false },
  { id: 'c48', suffix: 'ut', levelName: '蝴蝶谷', words: [{ text: 'cut', translation: '切', imageUrl: getImageUrl('cut') }, { text: 'nut', translation: '坚果', imageUrl: getImageUrl('nut') }, { text: 'shut', translation: '关闭', imageUrl: getImageUrl('shut') }], rhyme: '水果 cut (切), 加入 nut (坚果), 做完 shut (关闭).', learned: false },
  { id: 'c49', suffix: 'ill', levelName: '冰晶洞穴', words: [{ text: 'ill', translation: '生病的', imageUrl: getImageUrl('ill') }, { text: 'pill', translation: '药丸', imageUrl: getImageUrl('pill') }, { text: 'hill', translation: '小山', imageUrl: getImageUrl('hill') }], rhyme: '身体 ill (生病的), 买来 pill (药丸), 堆成 hill (小山), 欠下 bill (账单).', learned: false },
  { id: 'c50', suffix: 'ble', levelName: '冰晶洞穴', words: [{ text: 'table', translation: '桌子', imageUrl: getImageUrl('table') }, { text: 'trouble', translation: '麻烦', imageUrl: getImageUrl('trouble') }, { text: 'double', translation: '加倍', imageUrl: getImageUrl('double') }], rhyme: '安装 table (桌子), 碰到 trouble (麻烦), 努力 double (加倍).', learned: false },
  { id: 'c51', suffix: 'ble', levelName: '烈焰山脉', words: [{ text: 'bicycle', translation: '自行车', imageUrl: getImageUrl('bicycle') }, { text: 'uncle', translation: '叔叔', imageUrl: getImageUrl('uncle') }, { text: 'circle', translation: '圆', imageUrl: getImageUrl('circle') }], rhyme: '我家 uncle (叔叔), 骑着 bicycle (自行车), 绕着 circle (圆圈).', learned: false },
  { id: 'c52', suffix: 'dle', levelName: '烈焰山脉', words: [{ text: 'needle', translation: '针', imageUrl: getImageUrl('needle') }, { text: 'noodle', translation: '面条', imageUrl: getImageUrl('noodle') }, { text: 'candle', translation: '蜡烛', imageUrl: getImageUrl('candle') }], rhyme: '一根 needle (针), 掉进 noodle (面条), 点上 candle (蜡烛).', learned: false },
  { id: 'c53', suffix: 'gle', levelName: '翡翠湿地', words: [{ text: 'eagle', translation: '老鹰', imageUrl: getImageUrl('eagle') }, { text: 'angle', translation: '角', imageUrl: getImageUrl('angle') }, { text: 'jungle', translation: '丛林', imageUrl: getImageUrl('jungle') }], rhyme: '一只 eagle (老鹰), 特殊 angle (角), 冲进 jungle (丛林).', learned: false },
  { id: 'c54', suffix: 'ple', levelName: '翡翠湿地', words: [{ text: 'people', translation: '人们', imageUrl: getImageUrl('people') }, { text: 'apple', translation: '苹果', imageUrl: getImageUrl('apple') }, { text: 'temple', translation: '寺庙', imageUrl: getImageUrl('temple') }], rhyme: '这些 people (人们), 会在 temple (寺庙), 供奉 apple (苹果).', learned: false },
  { id: 'c55', suffix: 'tle', levelName: '黄金沙滩', words: [{ text: 'turtle', translation: '海龟', imageUrl: getImageUrl('turtle') }, { text: 'little', translation: '小', imageUrl: getImageUrl('little') }, { text: 'bottle', translation: '瓶子', imageUrl: getImageUrl('bottle') }], rhyme: '这只 turtle (海龟), 身材 little (小), 钻进 bottle (瓶子).', learned: false },
  { id: 'c56', suffix: 'ic', levelName: '黄金沙滩', words: [{ text: 'music', translation: '音乐', imageUrl: getImageUrl('music') }, { text: 'magic', translation: '魔术', imageUrl: getImageUrl('magic') }, { text: 'comic', translation: '漫画', imageUrl: getImageUrl('comic') }], rhyme: '听听 music (音乐), 变变 magic (魔术), 看看 comic (漫画), 野外 picnic (野餐).', learned: false },
  { id: 'c57', suffix: 'ack', levelName: '暗影峡谷', words: [{ text: 'back', translation: '背', imageUrl: getImageUrl('back') }, { text: 'attack', translation: '袭击', imageUrl: getImageUrl('attack') }, { text: 'black', translation: '黑的', imageUrl: getImageUrl('black') }], rhyme: '我的 back (背), 被人 attack (袭击), 眼睛 black (黑的).', learned: false },
  { id: 'c58', suffix: 'eck', levelName: '暗影峡谷', words: [{ text: 'neck', translation: '脖子', imageUrl: getImageUrl('neck') }, { text: 'check', translation: '检查', imageUrl: getImageUrl('check') }, { text: 'deck', translation: '甲板', imageUrl: getImageUrl('deck') }], rhyme: '转转 neck (脖子), 四周 check (检查), 站在 deck (甲板).', learned: false },
  { id: 'c59', suffix: 'ick', levelName: '极光之巅', words: [{ text: 'chick', translation: '小鸡', imageUrl: getImageUrl('chick') }, { text: 'quick', translation: '快的', imageUrl: getImageUrl('fast') }, { text: 'kick', translation: '踢', imageUrl: getImageUrl('kick') }], rhyme: '一只 chick (小鸡), 动作 quick (快), 把我 kick (踢).', learned: false },
  { id: 'c60', suffix: 'ick', levelName: '极光之巅', words: [{ text: 'quick', translation: '快的', imageUrl: getImageUrl('quick') }, { text: 'pick', translation: '捡起', imageUrl: getImageUrl('pick') }, { text: 'stick', translation: '木棍', imageUrl: getImageUrl('stick') }], rhyme: '速度 quick (快的), 赶紧 pick (捡起), 一根 stick (木棍).', learned: false },
  { id: 'c61', suffix: 'ick', levelName: '遗忘之城', words: [{ text: 'trick', translation: '捉弄', imageUrl: getImageUrl('trick') }, { text: 'lick', translation: '舔', imageUrl: getImageUrl('lick') }, { text: 'sick', translation: '恶心', imageUrl: getImageUrl('sick') }], rhyme: '被人 trick (捉弄), 把脚 lick (舔), 感到 sick (恶心).', learned: false },
  { id: 'c62', suffix: 'ock', levelName: '遗忘之城', words: [{ text: 'knock', translation: '敲', imageUrl: getImageUrl('knock') }, { text: 'lock', translation: '锁', imageUrl: getImageUrl('lock') }, { text: 'shock', translation: '吃惊', imageUrl: getImageUrl('shock') }], rhyme: '把门 knock (敲), 门没 lock (锁), 非常 shock (吃惊).', learned: false },
  { id: 'c63', suffix: 'ock', levelName: '梦幻岛', words: [{ text: 'sock', translation: '袜子', imageUrl: getImageUrl('socks') }, { text: 'rock', translation: '岩石', imageUrl: getImageUrl('rock') }, { text: 'mock', translation: '嘲笑', imageUrl: getImageUrl('mock') }], rhyme: '没穿 sock (袜子), 踩到 rock (岩石), 被人 mock (嘲笑).', learned: false },
  { id: 'c64', suffix: 'ock', levelName: '梦幻岛', words: [{ text: 'cock', translation: '公鸡', imageUrl: getImageUrl('rooster') }, { text: 'clock', translation: '钟', imageUrl: getImageUrl('clock') }], rhyme: '有了 cock (公鸡), 不用 clock (钟).', learned: false },
  { id: 'c65', suffix: 'uck', levelName: '机械迷城', words: [{ text: 'truck', translation: '卡车', imageUrl: getImageUrl('truck') }, { text: 'duck', translation: '鸭子', imageUrl: getImageUrl('duck') }, { text: 'luck', translation: '好运', imageUrl: getImageUrl('luck') }], rhyme: '一辆 truck (卡车), 满载 duck (鸭子), 一路 luck (好运).', learned: false },
  { id: 'c66', suffix: 'cket', levelName: '机械迷城', words: [{ text: 'jacket', translation: '夹克', imageUrl: getImageUrl('jacket') }, { text: 'ticket', translation: '票', imageUrl: getImageUrl('ticket') }, { text: 'pocket', translation: '口袋', imageUrl: getImageUrl('pocket') }], rhyme: '脱下 jacket (夹克), 忘记 ticket (票), 还在 pocket (口袋).', learned: false },
  { id: 'c67', suffix: 'cket', levelName: '糖果屋', words: [{ text: 'market', translation: '市场', imageUrl: getImageUrl('market') }, { text: 'bucket', translation: '桶', imageUrl: getImageUrl('bucket') }, { text: 'rocket', translation: '火箭', imageUrl: getImageUrl('rocket') }], rhyme: '到了 market (市场), 买了 bucket (桶), 装满 rocket (火箭).', learned: false },
  { id: 'c68', suffix: 'ch', levelName: '糖果屋', words: [{ text: 'lunch', translation: '午餐', imageUrl: getImageUrl('lunch') }, { text: 'rich', translation: '丰富的', imageUrl: getImageUrl('rich') }, { text: 'much', translation: '很多', imageUrl: getImageUrl('much') }], rhyme: '每次 lunch (午餐), 非常 rich (丰富的), 吃的 much (很多).', learned: false },
  { id: 'c69', suffix: 'ch', levelName: '魔法学院', words: [{ text: 'coach', translation: '教练', imageUrl: getImageUrl('coach') }, { text: 'teach', translation: '教', imageUrl: getImageUrl('teach') }, { text: 'speech', translation: '演讲', imageUrl: getImageUrl('speech') }], rhyme: '我的 coach (教练), 每天 teach (教), 我们 speech (演讲).', learned: false },
  { id: 'c70', suffix: 'ch', levelName: '魔法学院', words: [{ text: 'beach', translation: '海滩', imageUrl: getImageUrl('beach') }, { text: 'reach', translation: '到达', imageUrl: getImageUrl('reach') }, { text: 'search', translation: '搜寻', imageUrl: getImageUrl('search') }], rhyme: '想去 beach (海滩), 终于 reach (到达), 开始 search (搜寻).', learned: false },
  { id: 'c71', suffix: 'tch', levelName: '巨龙巢穴', words: [{ text: 'match', translation: '球赛', imageUrl: getImageUrl('match') }, { text: 'catch', translation: '抓住', imageUrl: getImageUrl('catch') }, { text: 'watch', translation: '观看', imageUrl: getImageUrl('watch') }], rhyme: '去看 match (球赛), 球没 catch (抓住), 不想 watch (观看).', learned: false },
  { id: 'c72', suffix: 'ash', levelName: '巨龙巢穴', words: [{ text: 'crash', translation: '坠毁', imageUrl: getImageUrl('crash') }, { text: 'ash', translation: '灰', imageUrl: getImageUrl('ash') }, { text: 'trash', translation: '垃圾', imageUrl: getImageUrl('trash') }, { text: 'cash', translation: '现金', imageUrl: getImageUrl('cash') }], rhyme: '飞机 crash (坠毁), 烧成 ash (灰), 变成 trash (垃圾), 浪费 cash (现金).', learned: false },
  { id: 'c73', suffix: 'ash', levelName: '凤凰涅槃', words: [{ text: 'trash', translation: '垃圾', imageUrl: getImageUrl('garbage') }, { text: 'ash', translation: '灰', imageUrl: getImageUrl('dust') }, { text: 'wash', translation: '洗', imageUrl: getImageUrl('wash') }], rhyme: '钻出 trash (垃圾), 满脸 ash (灰), 用水 wash (洗).', learned: false },
  { id: 'c74', suffix: 'ush', levelName: '凤凰涅槃', words: [{ text: 'blush', translation: '发红', imageUrl: getImageUrl('blush') }, { text: 'rush', translation: '冲', imageUrl: getImageUrl('rush') }, { text: 'bush', translation: '灌木丛', imageUrl: getImageUrl('bush') }], rhyme: '憋得 blush (发红), 拼命 rush (冲), 冲进 bush (灌木丛).', learned: false },
  { id: 'c75', suffix: 'ish', levelName: '独角兽之森', words: [{ text: 'wish', translation: '希望', imageUrl: getImageUrl('wish') }, { text: 'fish', translation: '鱼', imageUrl: getImageUrl('fish') }, { text: 'dish', translation: '菜', imageUrl: getImageUrl('dish') }], rhyme: '心中 wish (希望), 钓到 fish (鱼), 做成 dish (菜).', learned: false },
  { id: 'c76', suffix: 'ish', levelName: '独角兽之森', words: [{ text: 'finish', translation: '完成', imageUrl: getImageUrl('finish') }, { text: 'rubbish', translation: '垃圾', imageUrl: getImageUrl('rubbish') }, { text: 'vanish', translation: '消失', imageUrl: getImageUrl('vanish') }], rhyme: '打扫 finish (完成), 家里 rubbish (垃圾), 全部 vanish (消失).', learned: false },
  { id: 'c77', suffix: 'ush', levelName: '精灵之乡', words: [{ text: 'brush', translation: '刷子', imageUrl: getImageUrl('brush') }, { text: 'push', translation: '推', imageUrl: getImageUrl('push') }, { text: 'crush', translation: '压坏', imageUrl: getImageUrl('crush') }], rhyme: '用力 push (推), 一个 brush (刷子), 结果 crush (压坏).', learned: false },
  { id: 'c78', suffix: 'to', levelName: '精灵之乡', words: [{ text: 'tomato', translation: '西红柿', imageUrl: getImageUrl('tomato') }, { text: 'potato', translation: '土豆', imageUrl: getImageUrl('potato') }, { text: 'photo', translation: '照片', imageUrl: getImageUrl('photo') }], rhyme: '鸡蛋 tomato (西红柿), 酸辣 potato (土豆), 拍下 photo (照片).', learned: false },
  { id: 'c79', suffix: 'gh', levelName: '矮人矿坑', words: [{ text: 'laugh', translation: '笑', imageUrl: getImageUrl('laugh') }, { text: 'enough', translation: '足够的', imageUrl: getImageUrl('enough') }, { text: 'cough', translation: '咳嗽', imageUrl: getImageUrl('cough') }], rhyme: '喝酒 enough (足够的), 大声 laugh (笑), 不停 cough (咳嗽).', learned: false },
  { id: 'c80', suffix: 'ath', levelName: '矮人矿坑', words: [{ text: 'math', translation: '数学', imageUrl: getImageUrl('math') }, { text: 'path', translation: '小路', imageUrl: getImageUrl('path') }, { text: 'bath', translation: '洗澡', imageUrl: getImageUrl('bath') }], rhyme: '学完 math (数学), 穿过 path (小路), 洗个 bath (洗澡).', learned: false },
  { id: 'c81', suffix: 'eath', levelName: '天空之城', words: [{ text: 'breath', translation: '呼吸', imageUrl: getImageUrl('breath') }, { text: 'death', translation: '死亡', imageUrl: getImageUrl('death') }], rhyme: '没有 breath (呼吸), 已经 death (死亡).', learned: false },
  { id: 'c82', suffix: 'oth', levelName: '天空之城', words: [{ text: 'cloth', translation: '衣服', imageUrl: getImageUrl('cloth') }, { text: 'both', translation: '两者', imageUrl: getImageUrl('both') }], rhyme: '去买 cloth (衣服), 喜欢 both (两者).', learned: false },
  { id: 'c83', suffix: 'ooth', levelName: '月光湖畔', words: [{ text: 'booth', translation: '摊位', imageUrl: getImageUrl('booth') }, { text: 'tooth', translation: '牙齿', imageUrl: getImageUrl('tooth') }, { text: 'smooth', translation: '光滑的', imageUrl: getImageUrl('smooth') }], rhyme: '找个 booth (摊位), 洗个 tooth (牙齿), 感觉 smooth (光滑的).', learned: false },
  { id: 'c84', suffix: 'th', levelName: '月光湖畔', words: [{ text: 'youth', translation: '年轻', imageUrl: getImageUrl('youth') }, { text: 'mouth', translation: '嘴巴', imageUrl: getImageUrl('mouth') }, { text: 'truth', translation: '真相', imageUrl: getImageUrl('truth') }], rhyme: '因为 youth (年轻), 不顾 mouth (嘴巴), 敢讲 truth (真相).', learned: false },
  { id: 'c85', suffix: 'nny', levelName: '彩虹桥', words: [{ text: 'sunny', translation: '晴朗的', imageUrl: getImageUrl('sunny') }, { text: 'penny', translation: '便士', imageUrl: getImageUrl('penny') }, { text: 'funny', translation: '滑稽的', imageUrl: getImageUrl('funny') }], rhyme: '天气 sunny (晴朗的), 身无 penny (便士), 感觉 funny (滑稽的).', learned: false },
  { id: 'c86', suffix: 'nner', levelName: '彩虹桥', words: [{ text: 'runner', translation: '跑步者', imageUrl: getImageUrl('runner') }, { text: 'winner', translation: '赢家', imageUrl: getImageUrl('winner') }, { text: 'dinner', translation: '晚餐', imageUrl: getImageUrl('dinner') }], rhyme: '最快 runner (跑步者), 成了 winner (赢家), 享受 dinner (晚餐).', learned: false },
  { id: 'c87', suffix: 'ink', levelName: '奥林匹斯', words: [{ text: 'ink', translation: '墨水', imageUrl: getImageUrl('ink') }, { text: 'think', translation: '思考', imageUrl: getImageUrl('think') }, { text: 'drink', translation: '喝', imageUrl: getImageUrl('drink') }], rhyme: '拿起 ink (墨水), 不加 think (思考), 仰头 drink (喝).', learned: false },
  { id: 'c88', suffix: 'ank', levelName: '奥林匹斯', words: [{ text: 'tank', translation: '坦克', imageUrl: getImageUrl('tank') }, { text: 'bank', translation: '岸', imageUrl: getImageUrl('bank') }, { text: 'thank', translation: '感谢', imageUrl: getImageUrl('thank') }], rhyme: '敌人 tank (坦克), 撞上 bank (岸), 老天 thank (感谢).', learned: false },
  { id: 'c89', suffix: 'ink', levelName: '奥林匹斯', words: [{ text: 'sink', translation: '下沉', imageUrl: getImageUrl('sink') }, { text: 'link', translation: '链接', imageUrl: getImageUrl('link') }, { text: 'pink', translation: '粉色', imageUrl: getImageUrl('pink') }], rhyme: '石头 sink (下沉), 铁链 link (链接), 颜色 pink (粉色).', learned: false },
  { id: 'c90', suffix: 'ank', levelName: '奥林匹斯', words: [{ text: 'blank', translation: '空白', imageUrl: getImageUrl('blank') }, { text: 'rank', translation: '排名', imageUrl: getImageUrl('rank') }, { text: 'bank', translation: '银行', imageUrl: getImageUrl('bank') }], rhyme: '脑子 blank (空白), 掉了 rank (排名), 没钱 bank (银行).', learned: false },
  { id: 'c91', suffix: 'ong', levelName: '诸神黄昏', words: [{ text: 'song', translation: '歌', imageUrl: getImageUrl('song') }, { text: 'long', translation: '长', imageUrl: getImageUrl('long') }, { text: 'wrong', translation: '错', imageUrl: getImageUrl('wrong') }], rhyme: '一首 song (歌), 歌词 long (长), 总唱 wrong (错).', learned: false },
  { id: 'c92', suffix: 'ong', levelName: '诸神黄昏', words: [{ text: 'long', translation: '长', imageUrl: getImageUrl('long') }, { text: 'along', translation: '沿着', imageUrl: getImageUrl('along') }, { text: 'strong', translation: '强壮的', imageUrl: getImageUrl('strong') }], rhyme: '山路 long (长), 跑步 along (沿着), 身体 strong (强壮的).', learned: false },
  { id: 'c93', suffix: 'ace', levelName: '水晶宫', words: [{ text: 'lace', translation: '鞋带', imageUrl: getImageUrl('lace') }, { text: 'face', translation: '脸', imageUrl: getImageUrl('face') }, { text: 'race', translation: '比赛', imageUrl: getImageUrl('race') }], rhyme: '系好 lace (鞋带), 拍拍 face (脸), 参加 race (比赛).', learned: false },
  { id: 'c94', suffix: 'ace', levelName: '水晶宫', words: [{ text: 'space', translation: '太空', imageUrl: getImageUrl('space') }, { text: 'pace', translation: '步子', imageUrl: getImageUrl('pace') }, { text: 'grace', translation: '优雅', imageUrl: getImageUrl('grace') }], rhyme: '进入 space (太空), 迈出 pace (步子), 神态 grace (优雅).', learned: false },
  { id: 'c95', suffix: 'ace', levelName: '水晶宫', words: [{ text: 'trace', translation: '追踪', imageUrl: getImageUrl('trace') }, { text: 'race', translation: '赛跑', imageUrl: getImageUrl('race') }, { text: 'place', translation: '地方', imageUrl: getImageUrl('place') }], rhyme: '有人 trace (追踪), 赶紧 race (赛跑), 换个 place (地方).', learned: false },
  { id: 'c96', suffix: 'ake', levelName: '翡翠湖', words: [{ text: 'wake', translation: '起床', imageUrl: getImageUrl('wake') }, { text: 'lake', translation: '湖边', imageUrl: getImageUrl('lake') }, { text: 'snake', translation: '蛇', imageUrl: getImageUrl('snake') }], rhyme: '清晨 wake (起床), 来到 lake (湖边), 钓上 snake (蛇).', learned: false },
  { id: 'c97', suffix: 'ake', levelName: '翡翠湖', words: [{ text: 'bake', translation: '烘焙', imageUrl: getImageUrl('bake') }, { text: 'make', translation: '做', imageUrl: getImageUrl('make') }, { text: 'cake', translation: '蛋糕', imageUrl: getImageUrl('cake') }], rhyme: '擅长 bake (烘焙), 喜欢 make (做), 各种 cake (蛋糕).', learned: false },
  { id: 'c98', suffix: 'ake', levelName: '翡翠湖', words: [{ text: 'cake', translation: '蛋糕', imageUrl: getImageUrl('cake') }, { text: 'take', translation: '拿', imageUrl: getImageUrl('take') }, { text: 'shake', translation: '摇', imageUrl: getImageUrl('shake') }], rhyme: '买了 cake (蛋糕), 小心 take (拿), 不能 shake (摇).', learned: false },
  { id: 'c99', suffix: 'ale', levelName: '深海遗迹', words: [{ text: 'tale', translation: '传说', imageUrl: getImageUrl('tale') }, { text: 'male', translation: '男人', imageUrl: getImageUrl('male') }, { text: 'whale', translation: '鲸鱼', imageUrl: getImageUrl('whale') }], rhyme: '有个 tale (传说), 关于 male (男人), 战胜 whale (鲸鱼).', learned: false },
  { id: 'c100', suffix: 'ale', levelName: '深海遗迹', words: [{ text: 'gale', translation: '大风', imageUrl: getImageUrl('gale') }, { text: 'exhale', translation: '呼气', imageUrl: getImageUrl('exhale') }, { text: 'pale', translation: '苍白的', imageUrl: getImageUrl('pale') }], rhyme: '一阵 gale (大风), 无法 exhale (呼气), 脸色 pale (苍白的).', learned: false },
  { id: 'c101', suffix: 'ave', levelName: '海盗湾', words: [{ text: 'cave', translation: '山洞', imageUrl: getImageUrl('cave') }, { text: 'grave', translation: '坟墓', imageUrl: getImageUrl('grave') }, { text: 'brave', translation: '勇敢的', imageUrl: getImageUrl('brave') }], rhyme: '走进 cave (山洞), 看到 grave (坟墓), 不再 brave (勇敢的).', learned: false },
  { id: 'c102', suffix: 'ave', levelName: '海盗湾', words: [{ text: 'rave', translation: '怒吼', imageUrl: getImageUrl('rave') }, { text: 'wave', translation: '挥手', imageUrl: getImageUrl('wave') }, { text: 'save', translation: '救援', imageUrl: getImageUrl('save') }], rhyme: '大声 rave (怒吼), 把手 wave (挥手), 想被 save (救援).', learned: false },
  { id: 'c103', suffix: 'aid', levelName: '海盗湾', words: [{ text: 'aid', translation: '帮助', imageUrl: getImageUrl('aid') }, { text: 'afraid', translation: '害怕', imageUrl: getImageUrl('afraid') }], rhyme: '没人 aid (帮助), 也不 afraid (害怕).', learned: false },
  { id: 'c104', suffix: 'ail', levelName: '海盗湾', words: [{ text: 'tail', translation: '尾巴', imageUrl: getImageUrl('tail') }, { text: 'nail', translation: '钉子', imageUrl: getImageUrl('nail') }, { text: 'wail', translation: '大哭', imageUrl: getImageUrl('wail') }], rhyme: '它的 tail (尾巴), 碰到 nail (钉子), 大声 wail (大哭).', learned: false },
  { id: 'c105', suffix: 'ail', levelName: '海盗湾', words: [{ text: 'snail', translation: '蜗牛', imageUrl: getImageUrl('snail') }, { text: 'mail', translation: '邮件', imageUrl: getImageUrl('mail') }, { text: 'fail', translation: '失败', imageUrl: getImageUrl('fail') }], rhyme: '有只 snail (蜗牛), 发送 mail (邮件), 老是 fail (失败).', learned: false },
  { id: 'c106', suffix: 'ain', levelName: '勇者之路', words: [{ text: 'train', translation: '训练', imageUrl: getImageUrl('train') }, { text: 'pain', translation: '痛苦', imageUrl: getImageUrl('pain') }, { text: 'gain', translation: '收获', imageUrl: getImageUrl('gain') }], rhyme: '不停 train (训练), 没有 pain (痛苦), 哪有 gain (收获).', learned: false },
  { id: 'c107', suffix: 'ain', levelName: '勇者之路', words: [{ text: 'rain', translation: '下雨', imageUrl: getImageUrl('rain') }, { text: 'drain', translation: '下水道', imageUrl: getImageUrl('drain') }, { text: 'grain', translation: '谷物', imageUrl: getImageUrl('grain') }], rhyme: '突然 rain (下雨), 没修 drain (下水道), 淹没 grain (谷物).', learned: false },
  { id: 'c108', suffix: 'ait', levelName: '勇者之路', words: [{ text: 'bait', translation: '鱼饵', imageUrl: getImageUrl('bait') }, { text: 'wait', translation: '等待', imageUrl: getImageUrl('wait') }], rhyme: '丢下 bait (鱼饵), 慢慢 wait (等待).', learned: false },
  { id: 'c109', suffix: 'aise', levelName: '勇者之路', words: [{ text: 'raise', translation: '举起', imageUrl: getImageUrl('raise') }, { text: 'praise', translation: '表扬', imageUrl: getImageUrl('praise') }], rhyme: '小手 raise (举起), 老师 praise (表扬).', learned: false },
  { id: 'c110', suffix: 'ay', levelName: '勇者之路', words: [{ text: 'day', translation: '天', imageUrl: getImageUrl('day') }, { text: 'pay', translation: '工资', imageUrl: getImageUrl('pay') }, { text: 'say', translation: '说', imageUrl: getImageUrl('say') }], rhyme: '很多 day (天), 没发 pay (工资), 无话 say (说).', learned: false },
  { id: 'c111', suffix: 'ay', levelName: '欢乐谷', words: [{ text: 'gray', translation: '灰色', imageUrl: getImageUrl('gray') }, { text: 'play', translation: '玩', imageUrl: getImageUrl('play') }, { text: 'stay', translation: '待着', imageUrl: getImageUrl('stay') }], rhyme: '天空 gray (灰色), 无心 play (玩), 回家 stay (待着).', learned: false },
  { id: 'c112', suffix: 'ay', levelName: '欢乐谷', words: [{ text: 'way', translation: '路', imageUrl: getImageUrl('way') }, { text: 'bay', translation: '海湾', imageUrl: getImageUrl('bay') }, { text: 'clay', translation: '黏土', imageUrl: getImageUrl('clay') }], rhyme: '这条 way (路), 通向 bay (海湾), 去玩 clay (黏土).', learned: false },
  { id: 'c113', suffix: 'ay', levelName: '欢乐谷', words: [{ text: 'May', translation: '五月', imageUrl: getImageUrl('may') }, { text: 'hay', translation: '干草', imageUrl: getImageUrl('hay') }, { text: 'lay', translation: '下蛋', imageUrl: getImageUrl('lay') }], rhyme: '到了 May (五月), 找到 hay (干草), 把蛋 lay (下蛋).', learned: false },
  { id: 'c114', suffix: 'ay', levelName: '欢乐谷', words: [{ text: 'yesterday', translation: '昨天', imageUrl: getImageUrl('yesterday') }, { text: 'subway', translation: '地铁', imageUrl: getImageUrl('subway') }, { text: 'play', translation: '玩', imageUrl: getImageUrl('play') }], rhyme: 'yesterday (昨天), 坐 subway (地铁), 出去 play (玩).', learned: false },
  { id: 'c115', suffix: 'ee', levelName: '生命之树', words: [{ text: 'bee', translation: '蜜蜂', imageUrl: getImageUrl('bee') }, { text: 'tree', translation: '树', imageUrl: getImageUrl('tree') }, { text: 'see', translation: '看到', imageUrl: getImageUrl('see') }], rhyme: '一只 bee (蜜蜂), 躲进 tree (树), 没人 see (看到).', learned: false },
  { id: 'c116', suffix: 'ee', levelName: '生命之树', words: [{ text: 'agree', translation: '同意', imageUrl: getImageUrl('agree') }, { text: 'degree', translation: '程度', imageUrl: getImageUrl('degree') }, { text: 'free', translation: '免费', imageUrl: getImageUrl('free') }], rhyme: '当场 agree (同意), 一定 degree (程度), 价格 free (免费).', learned: false },
  { id: 'c117', suffix: 'ee', levelName: '生命之树', words: [{ text: 'see', translation: '看到', imageUrl: getImageUrl('see') }, { text: 'flee', translation: '逃跑', imageUrl: getImageUrl('flee') }, { text: 'free', translation: '自由', imageUrl: getImageUrl('free') }], rhyme: '没人 see (看到), 马上 flee (逃跑), 获得 free (自由).', learned: false },
  { id: 'c118', suffix: 'eed', levelName: '生命之树', words: [{ text: 'seed', translation: '种子', imageUrl: getImageUrl('seed') }, { text: 'weed', translation: '杂草', imageUrl: getImageUrl('weed') }, { text: 'feed', translation: '喂养', imageUrl: getImageUrl('feed') }], rhyme: '种下 seed (种子), 长出 weed (杂草), 把羊 feed (喂养).', learned: false },
  { id: 'c119', suffix: 'eed', levelName: '生命之树', words: [{ text: 'bleed', translation: '流血', imageUrl: getImageUrl('bleed') }, { text: 'speed', translation: '速度', imageUrl: getImageUrl('speed') }, { text: 'succeed', translation: '成功', imageUrl: getImageUrl('succeed') }], rhyme: '有人 bleed (流血), 加快 speed (速度), 救援 succeed (成功).', learned: false },
  { id: 'c120', suffix: 'eel', levelName: '钢铁之城', words: [{ text: 'steel', translation: '钢铁', imageUrl: getImageUrl('steel') }, { text: 'wheel', translation: '轮子', imageUrl: getImageUrl('wheel') }, { text: 'feel', translation: '感觉', imageUrl: getImageUrl('feel') }], rhyme: '我用 steel (钢铁), 造个 wheel (轮子), 自豪感 feel (感觉).', learned: false },
  { id: 'c121', suffix: 'een', levelName: '钢铁之城', words: [{ text: 'queen', translation: '女王', imageUrl: getImageUrl('queen') }, { text: 'screen', translation: '屏幕', imageUrl: getImageUrl('screen') }, { text: 'green', translation: '绿的', imageUrl: getImageUrl('green') }], rhyme: '一个 queen (女王), 对着 screen (屏幕), 脸色 green (绿的).', learned: false },
  { id: 'c122', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'deep', translation: '深', imageUrl: getImageUrl('deep') }, { text: 'jeep', translation: '吉普车', imageUrl: getImageUrl('jeep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }], rhyme: '悬崖 deep (深), 开着 jeep (吉普车), 莫要 sleep (睡着).', learned: false },
  { id: 'c123', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'steep', translation: '陡峭的', imageUrl: getImageUrl('steep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }, { text: 'weep', translation: '哭泣', imageUrl: getImageUrl('weep') }], rhyme: '悬崖 steep (陡峭的), 差点 sleep (睡着), 吓得 weep (哭泣).', learned: false },
  { id: 'c124', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'keep', translation: '保持', imageUrl: getImageUrl('keep') }, { text: 'sweep', translation: '打扫', imageUrl: getImageUrl('sweep') }, { text: 'creep', translation: '爬', imageUrl: getImageUrl('creep') }], rhyme: '卫生 keep (保持), 天天 sweep (打扫), 没虫 creep (爬).', learned: false },
  { id: 'c125', suffix: 'eep', levelName: '宁静湖畔', words: [{ text: 'sheep', translation: '羊', imageUrl: getImageUrl('sheep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }], rhyme: '数着 sheep (羊), 马上 sleep (睡着).', learned: false },
  { id: 'c126', suffix: 'eet', levelName: '宁静湖畔', words: [{ text: 'meet', translation: '见面', imageUrl: getImageUrl('meet') }, { text: 'street', translation: '街上', imageUrl: getImageUrl('street') }, { text: 'sweet', translation: '糖', imageUrl: getImageUrl('sweet') }], rhyme: '初次 meet (见面), 是在 street (街上), 给我 sweet (糖).', learned: false },
  { id: 'c127', suffix: 'ea', levelName: '宁静湖畔', words: [{ text: 'pea', translation: '豌豆', imageUrl: getImageUrl('pea') }, { text: 'sea', translation: '海', imageUrl: getImageUrl('sea') }, { text: 'tea', translation: '茶', imageUrl: getImageUrl('tea') }], rhyme: '来到 sea (海), 泡杯 tea (茶), 吃点 pea (豌豆).', learned: false },
  { id: 'c128', suffix: 'eak', levelName: '宁静湖畔', words: [{ text: 'weak', translation: '虚弱的', imageUrl: getImageUrl('weak') }, { text: 'peak', translation: '山顶', imageUrl: getImageUrl('peak') }, { text: 'speak', translation: '说话', imageUrl: getImageUrl('speak') }], rhyme: '身体 weak (虚弱的), 爬上 peak (山顶), 无力 speak (说话).', learned: false },
  { id: 'c129', suffix: 'eak', levelName: '宁静湖畔', words: [{ text: 'break', translation: '裂开', imageUrl: getImageUrl('break') }, { text: 'leak', translation: '泄露', imageUrl: getImageUrl('leak') }, { text: 'sneak', translation: '溜走', imageUrl: getImageUrl('sneak') }], rhyme: '管道 break (裂开), 煤气 leak (泄露), 赶紧 sneak (溜走).', learned: false },
  { id: 'c130', suffix: 'eam', levelName: '梦境森林', words: [{ text: 'dream', translation: '梦', imageUrl: getImageUrl('dream') }, { text: 'stream', translation: '小河', imageUrl: getImageUrl('stream') }, { text: 'scream', translation: '尖叫', imageUrl: getImageUrl('scream') }], rhyme: '做个 dream (梦), 掉进 stream (小河), 大声 scream (尖叫).', learned: false },
  { id: 'c131', suffix: 'ean', levelName: '梦境森林', words: [{ text: 'bean', translation: '豆', imageUrl: getImageUrl('bean') }, { text: 'clean', translation: '干净的', imageUrl: getImageUrl('clean') }], rhyme: '摘来 bean (豆), 处理 clean (干净的), 感觉 keen (敏锐的).', learned: false },
  { id: 'c132', suffix: 'eat', levelName: '梦境森林', words: [{ text: 'eat', translation: '吃', imageUrl: getImageUrl('eat') }, { text: 'meat', translation: '肉', imageUrl: getImageUrl('meat') }, { text: 'neat', translation: '干净的', imageUrl: getImageUrl('neat') }], rhyme: '收拾 neat (干净的), 开始 eat (吃), 各种 meat (肉).', learned: false },
  { id: 'c133', suffix: 'eat', levelName: '梦境森林', words: [{ text: 'cheat', translation: '作弊', imageUrl: getImageUrl('cheat') }, { text: 'beat', translation: '打', imageUrl: getImageUrl('beat') }, { text: 'seat', translation: '座位', imageUrl: getImageUrl('seat') }], rhyme: '不准 cheat (作弊), 把它 beat (打), 找个 seat (座位).', learned: false },
  { id: 'c134', suffix: 'eel', levelName: '钢铁之城', words: [{ text: 'steel', translation: '钢铁', imageUrl: getImageUrl('steel') }, { text: 'wheel', translation: '轮子', imageUrl: getImageUrl('wheel') }, { text: 'feel', translation: '感觉', imageUrl: getImageUrl('feel') }], rhyme: '我用 steel (钢铁), 造个 wheel (轮子), 自豪感 feel (感觉).', learned: false },
  { id: 'c135', suffix: 'een', levelName: '钢铁之城', words: [{ text: 'queen', translation: '女王', imageUrl: getImageUrl('queen') }, { text: 'screen', translation: '屏幕', imageUrl: getImageUrl('screen') }, { text: 'green', translation: '绿的', imageUrl: getImageUrl('green') }], rhyme: '一个 queen (女王), 对着 screen (屏幕), 脸色 green (绿的).', learned: false },
  { id: 'c136', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'deep', translation: '深', imageUrl: getImageUrl('deep') }, { text: 'jeep', translation: '吉普车', imageUrl: getImageUrl('jeep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }], rhyme: '悬崖 deep (深), 开着 jeep (吉普车), 莫要 sleep (睡着).', learned: false },
  { id: 'c137', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'steep', translation: '陡峭的', imageUrl: getImageUrl('steep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }, { text: 'weep', translation: '哭泣', imageUrl: getImageUrl('weep') }], rhyme: '悬崖 steep (陡峭的), 差点 sleep (睡着), 吓得 weep (哭泣).', learned: false },
  { id: 'c138', suffix: 'eep', levelName: '钢铁之城', words: [{ text: 'keep', translation: '保持', imageUrl: getImageUrl('keep') }, { text: 'sweep', translation: '打扫', imageUrl: getImageUrl('sweep') }, { text: 'creep', translation: '爬', imageUrl: getImageUrl('creep') }], rhyme: '卫生 keep (保持), 天天 sweep (打扫), 没虫 creep (爬).', learned: false },
  { id: 'c139', suffix: 'eep', levelName: '宁静湖畔', words: [{ text: 'sheep', translation: '羊', imageUrl: getImageUrl('sheep') }, { text: 'sleep', translation: '睡着', imageUrl: getImageUrl('sleep') }], rhyme: '数着 sheep (羊), 马上 sleep (睡着), 梦里 peep (偷看).', learned: false },
  { id: 'c140', suffix: 'eet', levelName: '宁静湖畔', words: [{ text: 'meet', translation: '见面', imageUrl: getImageUrl('meet') }, { text: 'street', translation: '街上', imageUrl: getImageUrl('street') }, { text: 'sweet', translation: '糖', imageUrl: getImageUrl('sweet') }], rhyme: '初次 meet (见面), 是在 street (街上), 给我 sweet (糖).', learned: false },
  { id: 'c141', suffix: 'ea', levelName: '宁静湖畔', words: [{ text: 'pea', translation: '豌豆', imageUrl: getImageUrl('pea') }, { text: 'sea', translation: '海', imageUrl: getImageUrl('sea') }, { text: 'tea', translation: '茶', imageUrl: getImageUrl('tea') }], rhyme: '来到 sea (海), 泡杯 tea (茶), 吃点 pea (豌豆).', learned: false },
  { id: 'c142', suffix: 'eak', levelName: '宁静湖畔', words: [{ text: 'weak', translation: '虚弱的', imageUrl: getImageUrl('weak') }, { text: 'peak', translation: '山顶', imageUrl: getImageUrl('peak') }, { text: 'speak', translation: '说话', imageUrl: getImageUrl('speak') }], rhyme: '身体 weak (虚弱的), 爬上 peak (山顶), 无力 speak (说话).', learned: false },
  { id: 'c143', suffix: 'eak', levelName: '宁静湖畔', words: [{ text: 'break', translation: '裂开', imageUrl: getImageUrl('break') }, { text: 'leak', translation: '泄露', imageUrl: getImageUrl('leak') }, { text: 'sneak', translation: '溜走', imageUrl: getImageUrl('sneak') }], rhyme: '管道 break (裂开), 煤气 leak (泄露), 赶紧 sneak (溜走).', learned: false },
  { id: 'c144', suffix: 'eam', levelName: '梦境森林', words: [{ text: 'dream', translation: '梦', imageUrl: getImageUrl('dream') }, { text: 'stream', translation: '小河', imageUrl: getImageUrl('stream') }, { text: 'scream', translation: '尖叫', imageUrl: getImageUrl('scream') }], rhyme: '做个 dream (梦), 掉进 stream (小河), 大声 scream (尖叫).', learned: false },
  { id: 'c145', suffix: 'ean', levelName: '梦境森林', words: [{ text: 'bean', translation: '豆', imageUrl: getImageUrl('bean') }, { text: 'clean', translation: '干净的', imageUrl: getImageUrl('clean') }], rhyme: '摘来 bean (豆), 处理 clean (干净的), 感觉 keen (敏锐的).', learned: false },
  { id: 'c146', suffix: 'eat', levelName: '梦境森林', words: [{ text: 'eat', translation: '吃', imageUrl: getImageUrl('eat') }, { text: 'meat', translation: '肉', imageUrl: getImageUrl('meat') }, { text: 'neat', translation: '干净的', imageUrl: getImageUrl('neat') }], rhyme: '收拾 neat (干净的), 开始 eat (吃), 各种 meat (肉).', learned: false },
  { id: 'c147', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'nice', translation: '好的', imageUrl: getImageUrl('nice') }, { text: 'rice', translation: '米饭', imageUrl: getImageUrl('rice') }, { text: 'mice', translation: '老鼠', imageUrl: getImageUrl('mice') }], rhyme: '味道 nice (好的), 喜欢 rice (米饭), 招来 mice (老鼠).', learned: false },
  { id: 'c148', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'price', translation: '价格', imageUrl: getImageUrl('price') }, { text: 'twice', translation: '两次', imageUrl: getImageUrl('twice') }, { text: 'slice', translation: '切片', imageUrl: getImageUrl('slice') }], rhyme: '问问 price (价格), 买了 twice (两次), 切成 slice (切片).', learned: false },
  { id: 'c149', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'ice', translation: '冰', imageUrl: getImageUrl('ice') }, { text: 'dice', translation: '骰子', imageUrl: getImageUrl('dice') }, { text: 'advice', translation: '建议', imageUrl: getImageUrl('advice') }], rhyme: '加点 ice (冰), 玩个 dice (骰子), 听听 advice (建议).', learned: false },
  { id: 'c150', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'voice', translation: '声音', imageUrl: getImageUrl('voice') }, { text: 'choice', translation: '选择', imageUrl: getImageUrl('choice') }], rhyme: '优美 voice (声音), 明智 choice (选择), 真是 rejoice (欣喜).', learned: false },
  { id: 'c151', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'service', translation: '服务', imageUrl: getImageUrl('service') }, { text: 'police', translation: '警察', imageUrl: getImageUrl('police') }], rhyme: '这种 service (服务), 叫来 police (警察), 真是 nice (好的).', learned: false },
  { id: 'c152', suffix: 'ice', levelName: '智慧神殿', words: [{ text: 'notice', translation: '注意', imageUrl: getImageUrl('notice') }, { text: 'office', translation: '办公室', imageUrl: getImageUrl('office') }], rhyme: '有个 notice (注意), 贴在 office (办公室), 别有 prejudice (偏见).', learned: false },
  { id: 'c153', suffix: 'ide', levelName: '婚礼教堂', words: [{ text: 'ride', translation: '骑车', imageUrl: getImageUrl('ride') }, { text: 'bride', translation: '新娘', imageUrl: getImageUrl('bride') }, { text: 'pride', translation: '自豪', imageUrl: getImageUrl('pride') }], rhyme: '骑车 ride (骑车), 接着 bride (新娘), 满脸 pride (自豪).', learned: false },
  { id: 'c154', suffix: 'ide', levelName: '婚礼教堂', words: [{ text: 'tide', translation: '潮水', imageUrl: getImageUrl('tide') }, { text: 'wide', translation: '宽阔的', imageUrl: getImageUrl('wide') }, { text: 'hide', translation: '躲藏', imageUrl: getImageUrl('hide') }], rhyme: 'tide (潮水), wide (宽阔的), 赶紧 hide (躲藏).', learned: false },
  { id: 'c155', suffix: 'ide', levelName: '婚礼教堂', words: [{ text: 'slide', translation: '滑梯', imageUrl: getImageUrl('slide') }, { text: 'glide', translation: '滑行', imageUrl: getImageUrl('glide') }, { text: 'side', translation: '旁边', imageUrl: getImageUrl('side') }], rhyme: '玩个 slide (滑梯), 顺势 glide (滑行), 停在 side (旁边).', learned: false },
  { id: 'c156', suffix: 'ife', levelName: '生活广场', words: [{ text: 'wife', translation: '妻子', imageUrl: getImageUrl('wife') }, { text: 'knife', translation: '小刀', imageUrl: getImageUrl('knife') }, { text: 'life', translation: '生活', imageUrl: getImageUrl('life') }], rhyme: '我的 wife (妻子), 拿着 knife (小刀), 享受 life (生活).', learned: false },
  { id: 'c157', suffix: 'ike', levelName: '生活广场', words: [{ text: 'like', translation: '喜欢', imageUrl: getImageUrl('like') }, { text: 'bike', translation: '自行车', imageUrl: getImageUrl('bike') }, { text: 'hike', translation: '徒步', imageUrl: getImageUrl('hike') }], rhyme: '非常 like (喜欢), 骑着 bike (自行车), 出去 hike (徒步).', learned: false },
  { id: 'c158', suffix: 'ile', levelName: '生活广场', words: [{ text: 'file', translation: '文件', imageUrl: getImageUrl('file') }, { text: 'pile', translation: '堆', imageUrl: getImageUrl('pile') }, { text: 'smile', translation: '微笑', imageUrl: getImageUrl('smile') }], rhyme: '整理 file (文件), 堆成 pile (堆), 露出 smile (微笑).', learned: false },
  { id: 'c159', suffix: 'ine', levelName: '松木林', words: [{ text: 'pine', translation: '松树', imageUrl: getImageUrl('pine') }, { text: 'vine', translation: '藤蔓', imageUrl: getImageUrl('vine') }, { text: 'wine', translation: '酒', imageUrl: getImageUrl('wine') }], rhyme: 'pine (松树), vine (藤蔓), 还有 wine (酒).', learned: false },
  { id: 'c160', suffix: 'ine', levelName: '松木林', words: [{ text: 'shine', translation: '发光', imageUrl: getImageUrl('shine') }, { text: 'line', translation: '线', imageUrl: getImageUrl('line') }, { text: 'fine', translation: '好的', imageUrl: getImageUrl('fine') }], rhyme: '阳光 shine (发光), 站成 line (线), 感觉 fine (好的).', learned: false },
  { id: 'c161', suffix: 'ipe', levelName: '松木林', words: [{ text: 'pipe', translation: '管子', imageUrl: getImageUrl('pipe') }, { text: 'wipe', translation: '擦拭', imageUrl: getImageUrl('wipe') }, { text: 'stripe', translation: '条纹', imageUrl: getImageUrl('stripe') }], rhyme: '拿起 pipe (管子), 用力 wipe (擦拭), 擦出 stripe (条纹).', learned: false },
  { id: 'c162', suffix: 'ire', levelName: '松木林', words: [{ text: 'fire', translation: '火', imageUrl: getImageUrl('fire') }, { text: 'hire', translation: '雇佣', imageUrl: getImageUrl('hire') }, { text: 'retire', translation: '退休', imageUrl: getImageUrl('retire') }], rhyme: '救过 fire (火), 被人 hire (雇佣), 已经 retire (退休).', learned: false },
  { id: 'c163', suffix: 'ire', levelName: '松木林', words: [{ text: 'wire', translation: '电线', imageUrl: getImageUrl('wire') }, { text: 'fire', translation: '火', imageUrl: getImageUrl('fire') }, { text: 'tire', translation: '轮胎', imageUrl: getImageUrl('tire') }], rhyme: 'wire (电线), fire (火), 烧坏 tire (轮胎).', learned: false },
  { id: 'c164', suffix: 'ise', levelName: '惊喜派对', words: [{ text: 'wise', translation: '聪明的', imageUrl: getImageUrl('wise') }, { text: 'advice', translation: '建议', imageUrl: getImageUrl('advice') }, { text: 'surprise', translation: '惊喜', imageUrl: getImageUrl('surprise') }], rhyme: '非常 wise (聪明的), 听从 advice (建议), 得到 surprise (惊喜).', learned: false },
  { id: 'c165', suffix: 'ite', levelName: '惊喜派对', words: [{ text: 'white', translation: '白色的', imageUrl: getImageUrl('white') }, { text: 'write', translation: '写字', imageUrl: getImageUrl('write') }, { text: 'invite', translation: '邀请', imageUrl: getImageUrl('invite') }], rhyme: '穿上 white (白色的), 开始 write (写字), 准备 invite (邀请).', learned: false },
  { id: 'c166', suffix: 'ite', levelName: '惊喜派对', words: [{ text: 'site', translation: '地点', imageUrl: getImageUrl('site') }, { text: 'kite', translation: '风筝', imageUrl: getImageUrl('kite') }], rhyme: '换个 site (地点), 去放 kite (风筝), 心情 quite (相当) 好.', learned: false },
  { id: 'c167', suffix: 'ive', levelName: '惊喜派对', words: [{ text: 'drive', translation: '开车', imageUrl: getImageUrl('drive') }, { text: 'alive', translation: '活着的', imageUrl: getImageUrl('alive') }], rhyme: '拼命 drive (开车), 依然 alive (活着的), 还要 strive (努力).', learned: false },
  { id: 'c168', suffix: 'ize', levelName: '惊喜派对', words: [{ text: 'prize', translation: '奖品', imageUrl: getImageUrl('prize') }, { text: 'realize', translation: '意识到', imageUrl: getImageUrl('realize') }], rhyme: '拿到 prize (奖品), 终于 realize (意识到), 真是 wise (聪明的).', learned: false },
  { id: 'c169', suffix: 'ie', levelName: '下午茶时间', words: [{ text: 'tie', translation: '领带', imageUrl: getImageUrl('tie') }, { text: 'lie', translation: '躺下', imageUrl: getImageUrl('lie') }, { text: 'pie', translation: '派', imageUrl: getImageUrl('pie') }], rhyme: '解开 tie (领带), 舒服 lie (躺下), 吃个 pie (派).', learned: false },
  { id: 'c170', suffix: 'ie', levelName: '下午茶时间', words: [{ text: 'lie', translation: '撒谎', imageUrl: getImageUrl('lie') }, { text: 'die', translation: '死', imageUrl: getImageUrl('die') }], rhyme: '老是 lie (撒谎), 没脸 die (死), 只能 tie (系) 领带.', learned: false },
  { id: 'c171', suffix: 'igh', levelName: '下午茶时间', words: [{ text: 'high', translation: '高的', imageUrl: getImageUrl('high') }, { text: 'sigh', translation: '叹气', imageUrl: getImageUrl('sigh') }], rhyme: '门槛 high (高的), 只能 sigh (叹气), 望着 sky (天空).', learned: false },
  { id: 'c172', suffix: 'ight', levelName: '星光大道', words: [{ text: 'night', translation: '夜晚', imageUrl: getImageUrl('night') }, { text: 'light', translation: '灯光', imageUrl: getImageUrl('light') }, { text: 'sight', translation: '景象', imageUrl: getImageUrl('sight') }], rhyme: '寂静 night (夜晚), 柔和 light (灯光), 迷人 sight (景象).', learned: false },
  { id: 'c173', suffix: 'ight', levelName: '星光大道', words: [{ text: 'right', translation: '右边', imageUrl: getImageUrl('right') }, { text: 'fight', translation: '打架', imageUrl: getImageUrl('fight') }, { text: 'bright', translation: '明亮的', imageUrl: getImageUrl('bright') }], rhyme: '看向 right (右边), 有人 fight (打架), 眼睛 bright (明亮的).', learned: false },
  { id: 'c174', suffix: 'ight', levelName: '星光大道', words: [{ text: 'flight', translation: '飞行', imageUrl: getImageUrl('flight') }, { text: 'height', translation: '高度', imageUrl: getImageUrl('height') }, { text: 'delight', translation: '高兴', imageUrl: getImageUrl('delight') }], rhyme: '开始 flight (飞行), 达到 height (高度), 满心 delight (高兴).', learned: false },
  { id: 'c175', suffix: 'y', levelName: '星光大道', words: [{ text: 'shy', translation: '害羞的', imageUrl: getImageUrl('shy') }, { text: 'try', translation: '尝试', imageUrl: getImageUrl('try') }, { text: 'fly', translation: '飞', imageUrl: getImageUrl('fly') }, { text: 'sky', translation: '天空', imageUrl: getImageUrl('sky') }], rhyme: '不再 shy (害羞的), 努力 try (尝试), fly (飞) 向 sky (天空).', learned: false },
  { id: 'c176', suffix: 'y', levelName: '星光大道', words: [{ text: 'fry', translation: '油炸', imageUrl: getImageUrl('fry') }, { text: 'cry', translation: '哭', imageUrl: getImageUrl('cry') }, { text: 'dry', translation: '干的', imageUrl: getImageUrl('dry') }], rhyme: '东西 fry (油炸), 辣得 cry (哭), 嗓子 dry (干的).', learned: false },
  { id: 'c177', suffix: 'oke', levelName: '可乐工厂', words: [{ text: 'coke', translation: '可乐', imageUrl: getImageUrl('coke') }, { text: 'joke', translation: '笑话', imageUrl: getImageUrl('joke') }, { text: 'choke', translation: '呛到', imageUrl: getImageUrl('choke') }], rhyme: '喝着 coke (可乐), 听着 joke (笑话), 差点 choke (呛到).', learned: false },
  { id: 'c178', suffix: 'oke', levelName: '可乐工厂', words: [{ text: 'smoke', translation: '烟', imageUrl: getImageUrl('smoke') }, { text: 'choke', translation: '窒息', imageUrl: getImageUrl('choke') }], rhyme: '一股 smoke (烟), 让人 choke (窒息), 真是 broke (破产了).', learned: false },
  { id: 'c179', suffix: 'one', levelName: '可乐工厂', words: [{ text: 'phone', translation: '电话', imageUrl: getImageUrl('phone') }, { text: 'tone', translation: '语气', imageUrl: getImageUrl('tone') }, { text: 'stone', translation: '石头', imageUrl: getImageUrl('stone') }], rhyme: '接个 phone (电话), 这种 tone (语气), 像个 stone (石头).', learned: false },
  { id: 'c180', suffix: 'ope', levelName: '可乐工厂', words: [{ text: 'rope', translation: '绳子', imageUrl: getImageUrl('rope') }, { text: 'hope', translation: '希望', imageUrl: getImageUrl('hope') }, { text: 'slope', translation: '斜坡', imageUrl: getImageUrl('slope') }], rhyme: '抓紧 rope (绳子), 抱着 hope (希望), 爬上 slope (斜坡).', learned: false },
  { id: 'c181', suffix: 'ore', levelName: '可乐工厂', words: [{ text: 'sore', translation: '疼痛', imageUrl: getImageUrl('sore') }, { text: 'store', translation: '商店', imageUrl: getImageUrl('store') }, { text: 'core', translation: '核心', imageUrl: getImageUrl('core') }], rhyme: '浑身 sore (疼痛), 走进 store (商店), 买个 core (核心).', learned: false },
  { id: 'c182', suffix: 'ore', levelName: '可乐工厂', words: [{ text: 'chore', translation: '杂活', imageUrl: getImageUrl('chore') }, { text: 'bore', translation: '无聊', imageUrl: getImageUrl('bore') }, { text: 'more', translation: '更多', imageUrl: getImageUrl('more') }], rhyme: '干点 chore (杂活), 觉得 bore (无聊), 想要 more (更多).', learned: false },
  { id: 'c183', suffix: 'ose', levelName: '玫瑰花园', words: [{ text: 'close', translation: '关上', imageUrl: getImageUrl('close') }, { text: 'nose', translation: '鼻子', imageUrl: getImageUrl('nose') }, { text: 'rose', translation: '玫瑰', imageUrl: getImageUrl('rose') }], rhyme: '眼睛 close (关上), 凑近 nose (鼻子), 闻闻 rose (玫瑰).', learned: false },
  { id: 'c184', suffix: 'old', levelName: '玫瑰花园', words: [{ text: 'gold', translation: '金子', imageUrl: getImageUrl('gold') }, { text: 'hold', translation: '拿着', imageUrl: getImageUrl('hold') }, { text: 'fold', translation: '折叠', imageUrl: getImageUrl('fold') }], rhyme: '一块 gold (金子), 紧紧 hold (拿着), 小心 fold (折叠).', learned: false },
  { id: 'c185', suffix: 'old', levelName: '玫瑰花园', words: [{ text: 'old', translation: '老的', imageUrl: getImageUrl('old') }, { text: 'cold', translation: '冷的', imageUrl: getImageUrl('cold') }], rhyme: '年纪 old (老的), 身体 cold (冷的), 故事 told (讲述).', learned: false },
  { id: 'c186', suffix: 'oat', levelName: '玫瑰花园', words: [{ text: 'oat', translation: '燕麦', imageUrl: getImageUrl('oat') }, { text: 'throat', translation: '喉咙', imageUrl: getImageUrl('throat') }], rhyme: '吃点 oat (燕麦), 保护 throat (喉咙), 穿着 coat (外套).', learned: false },
  { id: 'c187', suffix: 'oat', levelName: '玫瑰花园', words: [{ text: 'goat', translation: '山羊', imageUrl: getImageUrl('goat') }, { text: 'coat', translation: '外套', imageUrl: getImageUrl('coat') }, { text: 'boat', translation: '小船', imageUrl: getImageUrl('boat') }, { text: 'float', translation: '漂浮', imageUrl: getImageUrl('float') }], rhyme: '一只 goat (山羊), 穿着 coat (外套), 坐在 boat (小船), 水上 float (漂浮).', learned: false },
  { id: 'c188', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'window', translation: '窗户', imageUrl: getImageUrl('window') }, { text: 'know', translation: '知道', imageUrl: getImageUrl('know') }, { text: 'snow', translation: '雪', imageUrl: getImageUrl('snow') }], rhyme: '打开 window (窗户), 已经 know (知道), 开始 snow (雪).', learned: false },
  { id: 'c189', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'show', translation: '展示', imageUrl: getImageUrl('show') }, { text: 'row', translation: '划船', imageUrl: getImageUrl('row') }], rhyme: '给我 show (展示), 怎么 row (划船), 动作 slow (慢的).', learned: false },
  { id: 'c190', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'below', translation: '在下面', imageUrl: getImageUrl('below') }, { text: 'shadow', translation: '影子', imageUrl: getImageUrl('shadow') }], rhyme: '就在 below (在下面), 看到 shadow (影子), 正在 grow (生长).', learned: false },
  { id: 'c191', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'blow', translation: '吹', imageUrl: getImageUrl('blow') }, { text: 'flow', translation: '流动', imageUrl: getImageUrl('flow') }, { text: 'glow', translation: '发光', imageUrl: getImageUrl('glow') }, { text: 'grow', translation: '生长', imageUrl: getImageUrl('grow') }], rhyme: '风在 blow (吹), 水在 flow (流动), 灯在 glow (发光), 树在 grow (生长).', learned: false },
  { id: 'c192', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'flow', translation: '流动', imageUrl: getImageUrl('flow') }, { text: 'low', translation: '低的', imageUrl: getImageUrl('low') }, { text: 'slow', translation: '慢的', imageUrl: getImageUrl('slow') }], rhyme: '溪水 flow (流动), 水位 low (低的), 动作 slow (慢的).', learned: false },
  { id: 'c193', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'willow', translation: '柳树', imageUrl: getImageUrl('willow') }, { text: 'yellow', translation: '黄色的', imageUrl: getImageUrl('yellow') }, { text: 'pillow', translation: '枕头', imageUrl: getImageUrl('pillow') }], rhyme: 'willow (柳树), yellow (黄色的), 靠着 pillow (枕头).', learned: false },
  { id: 'c194', suffix: 'ow', levelName: '冰雪奇缘', words: [{ text: 'crow', translation: '乌鸦', imageUrl: getImageUrl('crow') }, { text: 'borrow', translation: '借', imageUrl: getImageUrl('borrow') }, { text: 'arrow', translation: '箭', imageUrl: getImageUrl('arrow') }], rhyme: '一只 crow (乌鸦), 想要 borrow (借), 一支 arrow (箭).', learned: false },
  { id: 'c195', suffix: 'ue', levelName: '蓝色多瑙河', words: [{ text: 'due', translation: '到期', imageUrl: getImageUrl('due') }, { text: 'cue', translation: '提示', imageUrl: getImageUrl('cue') }], rhyme: '已经 due (到期), 给我 cue (提示), 看到 blue (蓝色的).', learned: false },
  { id: 'c196', suffix: 'ue', levelName: '蓝色多瑙河', words: [{ text: 'glue', translation: '胶水', imageUrl: getImageUrl('glue') }, { text: 'clue', translation: '线索', imageUrl: getImageUrl('clue') }, { text: 'blue', translation: '蓝色的', imageUrl: getImageUrl('blue') }], rhyme: '用了 glue (胶水), 找到 clue (线索), 脸色 blue (蓝色的).', learned: false },
  { id: 'c197', suffix: 'ew', levelName: '蓝色多瑙河', words: [{ text: 'dew', translation: '露水', imageUrl: getImageUrl('dew') }, { text: 'few', translation: '一些', imageUrl: getImageUrl('few') }, { text: 'new', translation: '新的', imageUrl: getImageUrl('new') }], rhyme: '晶莹 dew (露水), 采摘 few (一些), 感觉 new (新的).', learned: false },
  { id: 'c198', suffix: 'ui', levelName: '蓝色多瑙河', words: [{ text: 'suit', translation: '西装', imageUrl: getImageUrl('suit') }, { text: 'fruit', translation: '水果', imageUrl: getImageUrl('fruit') }], rhyme: '穿上 suit (西装), 吃点 fruit (水果), 真是 recruit (招募).', learned: false },
  { id: 'c199', suffix: 'oo', levelName: '动物乐园', words: [{ text: 'zoo', translation: '动物园', imageUrl: getImageUrl('zoo') }, { text: 'bamboo', translation: '竹子', imageUrl: getImageUrl('bamboo') }, { text: 'kangaroo', translation: '袋鼠', imageUrl: getImageUrl('kangaroo') }], rhyme: '进了 zoo (动物园), 看到 bamboo (竹子), 还有 kangaroo (袋鼠).', learned: false },
  { id: 'c200', suffix: 'oon', levelName: '动物乐园', words: [{ text: 'noon', translation: '中午', imageUrl: getImageUrl('noon') }, { text: 'balloon', translation: '气球', imageUrl: getImageUrl('balloon') }, { text: 'moon', translation: '月亮', imageUrl: getImageUrl('moon') }], rhyme: '到了 noon (中午), 飞走 balloon (气球), 升起 moon (月亮).', learned: false }
];

export const INITIAL_GROUPS: WordGroup[] = ALL_CARDS.map(card => ({
  id: card.id,
  title: `${card.suffix.toUpperCase()} 魔法卡`,
  suffix: card.suffix,
  words: card.words,
  rhyme: card.rhyme,
  learned: card.learned,
  srsLevel: 0,
  nextReview: 0
}));

export const INITIAL_VIDEOS: VideoLesson[] = [
  { 
    id: 'v1', 
    title: 'Phonics 精选视频：元音学习', 
    url: 'https://www.youtube.com/embed/HQ3G_O_YPrY', 
    thumbnail: 'https://picsum.photos/seed/vid1/400/225' 
  }
];

const constants = {
  ALL_CARDS,
  INITIAL_GROUPS,
  INITIAL_VIDEOS,
  CHARACTERS,
  SHOP_ITEMS
};

export default constants;
